Repository sensu/sensu-docs, pull requests merged in 2018-03, with the labels that each got.

#231 Updates to why and how to get involved
  README.md
Labels: in progress

#230 Add static.json for use with static buildpack
  static.json
Labels: in progress

#235 update changelog for enterprise 2.8.1 and later
  content/sensu-enterprise/2.8/changelog.md
Labels: in progress

#234 remove search index from version control
  .gitignore
  static/js/lunr/PagesIndex.json
Labels: in progress

#214 Entities reference guide
  content/sensu-core/2.0/reference/entities.md
Labels: in progress

#223 Add Assets reference documentation.
  content/sensu-core/2.0/reference/assets.md
Labels: in progress

#251 add core release notes for 1.2.1
  content/sensu-core/1.2/changelog.md
Labels: in progress

#250 Fix miscellaneous issues with installation docs
  content/sensu-core/0.29/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/0.29/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/0.29/installation/install-rabbitmq.md
  content/sensu-core/0.29/installation/install-redis-on-rhel-centos.md
  content/sensu-core/0.29/installation/install-redis-on-ubuntu-debian.md
  content/sensu-core/0.29/installation/install-redis.md
  content/sensu-core/0.29/installation/install-sensu-client.md
  content/sensu-core/0.29/installation/install-sensu-server-api.md
  content/sensu-core/0.29/installation/installation-overview.md
  content/sensu-core/0.29/installation/installation-prerequisites.md
  content/sensu-core/0.29/installation/installation-strategies.md
  content/sensu-core/0.29/installation/testing-prereleases.md
  content/sensu-core/0.29/installation/upgrading.md
  content/sensu-core/1.0/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.0/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.0/installation/install-rabbitmq.md
  content/sensu-core/1.0/installation/install-redis-on-rhel-centos.md
  content/sensu-core/1.0/installation/install-redis-on-ubuntu-debian.md
  content/sensu-core/1.0/installation/install-redis.md
  content/sensu-core/1.0/installation/install-sensu-client.md
  content/sensu-core/1.0/installation/install-sensu-server-api.md
  content/sensu-core/1.0/installation/installation-overview.md
  content/sensu-core/1.0/installation/installation-prerequisites.md
  content/sensu-core/1.0/installation/installation-strategies.md
  content/sensu-core/1.0/installation/testing-prereleases.md
  content/sensu-core/1.0/installation/upgrading.md
  content/sensu-core/1.1/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.1/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.1/installation/install-rabbitmq.md
  content/sensu-core/1.1/installation/install-redis-on-rhel-centos.md
  content/sensu-core/1.1/installation/install-redis-on-ubuntu-debian.md
  content/sensu-core/1.1/installation/install-redis.md
  content/sensu-core/1.1/installation/install-sensu-client.md
  content/sensu-core/1.1/installation/install-sensu-server-api.md
  content/sensu-core/1.1/installation/installation-overview.md
  content/sensu-core/1.1/installation/installation-prerequisites.md
  content/sensu-core/1.1/installation/installation-strategies.md
  content/sensu-core/1.1/installation/testing-prereleases.md
  content/sensu-core/1.1/installation/upgrading.md
  content/sensu-core/1.2/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.2/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.2/installation/install-rabbitmq.md
  content/sensu-core/1.2/installation/install-redis-on-rhel-centos.md
  content/sensu-core/1.2/installation/install-redis-on-ubuntu-debian.md
  content/sensu-core/1.2/installation/install-redis.md
  content/sensu-core/1.2/installation/install-sensu-client.md
  content/sensu-core/1.2/installation/install-sensu-server-api.md
  content/sensu-core/1.2/installation/installation-overview.md
  content/sensu-core/1.2/installation/installation-prerequisites.md
  content/sensu-core/1.2/installation/installation-strategies.md
  content/sensu-core/1.2/installation/testing-prereleases.md
  content/sensu-core/1.2/installation/upgrading.md
Labels: ready-for-review

#252 change baseurl to docs.sensu.io, add analytics
  config.toml
Labels: in progress

#247 Added mutators reference documentation
  content/sensu-core/2.0/overview/silencing.md
  content/sensu-core/2.0/reference/mutators.md
Labels: in progress, ready-for-review

#248 Sensu go/silencing
  content/sensu-core/2.0/reference/silencing.md
Labels: in progress, ready-for-review

#256 Custom 404 page
  layouts/404.html
  static.json
  static/stylesheets/override.css
Labels: in progress

#254 Refactor the Sensu 2 installation docs
  config.toml
  content/sensu-core/2.0/getting-started/installation-and-configuration.md
  layouts/_default/single.html
Labels: in progress

#238 Add filters documentation
  content/sensu-core/2.0/guides/reduce-alert-fatigue.md
  content/sensu-core/2.0/reference/filters.md
Labels: in progress

#236 add legacy pages for core, enterprise and dashboard products
  content/sensu-core/legacy.md
  content/sensu-enterprise-dashboard/legacy.md
  content/sensu-enterprise/legacy.md
Labels: in progress

#255 Add guide and reference documentation for checks
  content/sensu-core/2.0/guides/checks.md
  content/sensu-core/2.0/overview/checks.md
  content/sensu-core/2.0/reference/checks.md
  content/sensu-core/2.0/reference/silencing.md
Labels: in progress

#257 Add silencing guide
  content/sensu-core/2.0/guides/plan-a-maintenance.md
  content/sensu-core/2.0/overview/silencing.md
  content/sensu-core/2.0/reference/silencing.md
Labels: in progress, ready-for-review

#261 add github live editor link
  layouts/partials/drawer.html
Labels: ready-for-review

#273 Mark active element in navigation
  layouts/partials/nav.html
Labels: in progress

#262 remove author site param to disable "author" links in drawer
  config.toml
Labels: in progress

#271 Hooks reference refactoring
  content/sensu-core/2.0/reference/checks.md
  content/sensu-core/2.0/reference/filters.md
  content/sensu-core/2.0/reference/hooks.md
Labels: in progress

#237 Updates to why and how to get involved
  README.md
Labels: in progress, ready-for-review

#272 Ignore sensu-doc-template.md when rendering
  config.toml
Labels: in progress, ready-for-review

#288 [Search] Ensure no null entries are added to index
  Gruntfile.js
  package.json
Labels: bug, in progress

#278 Add auto-remediation guide for Sensu Core 2.0
  content/sensu-core/2.0/guides/monitor-server-resources.md
  content/sensu-core/2.0/guides/run-auto-remediation.md
Labels: in progress

#290 Fix platforms filenames
  content/sensu-core/0.29/platforms/sensu-on-freebsd.md
  content/sensu-core/0.29/platforms/sensu-on-mac-os-x.md
  content/sensu-core/0.29/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.0/platforms/sensu-on-freebsd.md
  content/sensu-core/1.0/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.0/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.1/platforms/sensu-on-freebsd.md
  content/sensu-core/1.1/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.1/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.2/platforms/sensu-on-freebsd.md
  content/sensu-core/1.2/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.2/platforms/sensu-on-microsoft-windows.md
Labels: in progress

#291 Update read-only user guide
  content/sensu-core/2.0/guides/create-read-only-user.md
Labels: in progress, ready-for-review

#260 add protected-mode no to sentinel.conf static files
  content/sensu-core/0.29/files/sentinel.conf
  content/sensu-core/1.0/files/sentinel.conf
  content/sensu-core/1.1/files/sentinel.conf
  content/sensu-core/1.2/files/sentinel.conf
Labels: in progress

#299 Updating snmp frontmatter
  content/sensu-core/0.29/guides/snmp-sensu-guide.md
  content/sensu-core/1.0/guides/snmp-sensu-guide.md
  content/sensu-core/1.1/guides/snmp-sensu-guide.md
  content/sensu-core/1.2/guides/snmp-sensu-guide.md
Labels: ready-for-review

#286 Updating Docs to ES Styles
  .gitignore
  config.toml
  content/sensu-core/0.29/faq.md
  content/sensu-core/1.0/faq.md
  content/sensu-core/1.1/faq.md
  content/sensu-core/1.2/faq.md
  layouts/_default/base-for-directory-listing.html
  layouts/_default/product-platforms.html
  layouts/_default/product-versions.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/drawer.html
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/header.html
  layouts/partials/nav.html
  static/images/favicon.ico
  static/images/favicon.png
  static/images/footer-symbol.png
  static/images/sensu-logo-icon-dark@2x.png
  static/images/sensu-logo-icon@2x.png
  static/stylesheets/docs-overrides.css
  static/stylesheets/homepage.css
  static/stylesheets/override.css
Labels: in progress

#304 Refactored events reference documentation
  content/sensu-core/2.0/reference/events.md
Labels: in progress, ready-for-review

#305 updating to sensu.io
  layouts/partials/footer.html
Labels: in progress

#303 [config] set enableRobotsTXT to true
  config.toml
Labels: ready-for-review

#301 fix broken mib links for snmp integration
  content/sensu-core/1.2/files/RFC-1212-MIB.txt
  content/sensu-core/1.2/files/RFC-1215-MIB.txt
  content/sensu-core/1.2/files/SENSU-ENTERPRISE-NOTIFY-MIB.txt
  content/sensu-core/1.2/files/SENSU-ENTERPRISE-ROOT-MIB.txt
  content/sensu-core/1.2/files/SENSU-ENTERPRISE-V1-MIB.txt
  content/sensu-enterprise/2.6/files/RFC-1212-MIB.txt
  content/sensu-enterprise/2.6/files/RFC-1215-MIB.txt
  content/sensu-enterprise/2.6/files/SENSU-ENTERPRISE-NOTIFY-MIB.txt
  content/sensu-enterprise/2.6/files/SENSU-ENTERPRISE-ROOT-MIB.txt
  content/sensu-enterprise/2.6/files/SENSU-ENTERPRISE-V1-MIB.txt
  content/sensu-enterprise/2.6/integrations/snmp.md
  content/sensu-enterprise/2.7/files/RFC-1212-MIB.txt
  content/sensu-enterprise/2.7/files/RFC-1215-MIB.txt
  content/sensu-enterprise/2.7/files/SENSU-ENTERPRISE-NOTIFY-MIB.txt
  content/sensu-enterprise/2.7/files/SENSU-ENTERPRISE-ROOT-MIB.txt
  content/sensu-enterprise/2.7/files/SENSU-ENTERPRISE-V1-MIB.txt
  content/sensu-enterprise/2.7/integrations/snmp.md
  content/sensu-enterprise/2.8/files/RFC-1212-MIB.txt
  content/sensu-enterprise/2.8/files/RFC-1215-MIB.txt
  content/sensu-enterprise/2.8/files/SENSU-ENTERPRISE-NOTIFY-MIB.txt
  content/sensu-enterprise/2.8/files/SENSU-ENTERPRISE-ROOT-MIB.txt
  content/sensu-enterprise/2.8/files/SENSU-ENTERPRISE-V1-MIB.txt
  content/sensu-enterprise/2.8/integrations/snmp.md
Labels: ready-for-review

#302 remove duplicated sensu-doc-template.md, restore old path
  content/sensu-core/1.0/files/sensu-doc-template.md
  content/sensu-core/1.1/files/sensu-doc-template.md
  content/sensu-core/1.2/files/sensu-doc-template.md
  static/files/sensu-doc-template.md
Labels: ready-for-review

#289 Update project documentation to reflect renamed repository
  CONTRIBUTING.md
  README.md
  config.toml
  package.json
Labels: in progress, ready-for-review

#292 Added reference guide for sensuctl.
  content/sensu-core/2.0/getting-started/configuring-sensuctl.md
  content/sensu-core/2.0/reference/sensuctl.md
Labels: in progress, ready-for-review
