Repository sensu/sensu-docs, pull requests merged in 2018-04, with the labels that each got.

#315 Implement GitHub CODEOWNERS file
  .github/CODEOWNERS
Labels: ready-for-review, review

#317 Add "latest" redirect for plugins
  static.json
Labels: ready-for-review, review

#320 Handlers reference documentation
  content/sensu-core/2.0/reference/handlers.md
Labels: ready-for-review, review

#322 Core/fix/client broken links
  content/sensu-core/0.29/guides/adding-a-client.md
  content/sensu-core/0.29/guides/intro-to-checks.md
  content/sensu-core/1.0/guides/adding-a-client.md
  content/sensu-core/1.0/guides/intro-to-checks.md
  content/sensu-core/1.1/guides/adding-a-client.md
  content/sensu-core/1.1/guides/intro-to-checks.md
  content/sensu-core/1.2/guides/adding-a-client.md
  content/sensu-core/1.2/guides/intro-to-checks.md
Labels: ready-for-review, review

#323 Refactored asset reference and created asset guide
  content/sensu-core/2.0/guides/install-check-executables-with-assets.md
  content/sensu-core/2.0/reference/assets.md
Labels: ready-for-review

#326 Add proxy entities guide
  content/sensu-core/2.0/guides/monitor-external-resources.md
Labels: ready-for-review

#333 Sensu go/links and cleanup
  content/sensu-core/2.0/getting-started/configuring-sensuctl.md
  content/sensu-core/2.0/getting-started/installation-and-configuration.md
  content/sensu-core/2.0/guides/create-read-only-user.md
  content/sensu-core/2.0/guides/monitor-server-resources.md
  content/sensu-core/2.0/guides/plan-a-maintenance.md
  content/sensu-core/2.0/guides/reduce-alert-fatigue.md
  content/sensu-core/2.0/guides/send-slack-alerts.md
  content/sensu-core/2.0/reference/checks.md
Labels: ready-for-review

#328 Sensu go/entities
  content/sensu-core/2.0/reference/entities.md
Labels: ready-for-review

#334 restore "Edit this page" link in drawer partial
  layouts/partials/drawer.html
Labels: ready-for-review

#345 Use HTTP 302 response when redirecting to "latest"
  static.json
Labels: ready-for-review

#342 Updating FAQ to fix #308 & #309
  content/sensu-core/0.29/faq.md
  content/sensu-core/1.0/faq.md
  content/sensu-core/1.1/faq.md
  content/sensu-core/1.2/faq.md
  content/sensu-core/1.3/faq.md
Labels: ready-for-review

#347 Updated 1.3. frontmatter for changelog
  content/sensu-core/1.3/changelog.md
Labels: ready-for-review

#343 Updating overview to fix #331
  content/sensu-enterprise/2.6/_index.md
  content/sensu-enterprise/2.7/_index.md
  content/sensu-enterprise/2.8/_index.md
Labels: ready-for-review

#344 Updating docs to reflect FreeBSD support #330
  content/sensu-core/0.29/platforms/sensu-on-freebsd.md
  content/sensu-core/1.0/platforms/sensu-on-freebsd.md
  content/sensu-core/1.1/platforms/sensu-on-freebsd.md
  content/sensu-core/1.2/platforms/sensu-on-freebsd.md
  content/sensu-core/1.3/platforms/sensu-on-freebsd.md
Labels: ready-for-review

#350 Updated changelog to reflect SSL change in 0.27
  content/sensu-core/0.29/changelog.md
  content/sensu-core/1.0/changelog.md
  content/sensu-core/1.1/changelog.md
  content/sensu-core/1.2/changelog.md
Labels: ready-for-review

#353 Updating docs where "product" is missing
  content/sensu-core/0.29/guides/intro-to-checks.md
  content/sensu-core/0.29/guides/intro-to-filters.md
  content/sensu-core/0.29/guides/intro-to-handlers.md
  content/sensu-core/0.29/guides/intro-to-mutators.md
  content/sensu-core/0.29/guides/overview.md
  content/sensu-core/0.29/installation/install-rabbitmq.md
  content/sensu-core/0.29/installation/install-redis.md
  content/sensu-core/1.0/guides/intro-to-filters.md
  content/sensu-core/1.0/guides/intro-to-handlers.md
  content/sensu-core/1.0/guides/intro-to-mutators.md
  content/sensu-core/1.0/guides/overview.md
  content/sensu-core/1.0/installation/install-rabbitmq.md
  content/sensu-core/1.0/installation/install-redis.md
  content/sensu-core/1.1/guides/intro-to-checks.md
  content/sensu-core/1.1/guides/intro-to-filters.md
  content/sensu-core/1.1/guides/intro-to-handlers.md
  content/sensu-core/1.1/guides/intro-to-mutators.md
  content/sensu-core/1.1/guides/overview.md
  content/sensu-core/1.1/installation/install-rabbitmq.md
  content/sensu-core/1.1/installation/install-redis.md
  content/sensu-core/1.2/guides/intro-to-checks.md
  content/sensu-core/1.2/guides/intro-to-filters.md
  content/sensu-core/1.2/guides/intro-to-handlers.md
  content/sensu-core/1.2/guides/intro-to-mutators.md
  content/sensu-core/1.2/guides/overview.md
  content/sensu-core/1.2/installation/install-rabbitmq.md
  content/sensu-core/1.2/installation/install-redis.md
  content/sensu-core/1.3/guides/intro-to-checks.md
  content/sensu-core/1.3/guides/intro-to-filters.md
  content/sensu-core/1.3/guides/intro-to-handlers.md
  content/sensu-core/1.3/guides/intro-to-mutators.md
  content/sensu-core/1.3/guides/overview.md
  content/sensu-core/1.3/installation/install-rabbitmq.md
  content/sensu-core/1.3/installation/install-redis.md
Labels: ready-for-review

#357 Adding indexes to subsections
  content/sensu-core/0.29/guides/_index.md
  content/sensu-core/0.29/installation/_index.md
  content/sensu-core/0.29/overview/_index.md
  content/sensu-core/0.29/platforms/_index.md
  content/sensu-core/0.29/quick-start/_index.md
  content/sensu-core/0.29/reference/_index.md
  content/sensu-core/1.0/guides/_index.md
  content/sensu-core/1.0/installation/_index.md
  content/sensu-core/1.0/overview/_index.md
  content/sensu-core/1.0/platforms/_index.md
  content/sensu-core/1.0/quick-start/_index.md
  content/sensu-core/1.1/guides/_index.md
  content/sensu-core/1.1/installation/_index.md
  content/sensu-core/1.1/overview/_index.md
  content/sensu-core/1.1/platforms/_index.md
  content/sensu-core/1.1/quick-start/_index.md
  content/sensu-core/1.1/reference/_index.md
  content/sensu-core/1.2/guides/_index.md
  content/sensu-core/1.2/installation/_index.md
  content/sensu-core/1.2/overview/_index.md
  content/sensu-core/1.2/platforms/_index.md
  content/sensu-core/1.2/quick-start/_index.md
  content/sensu-core/1.2/reference/_index.md
  content/sensu-core/1.3/guides/_index.md
  content/sensu-core/1.3/installation/_index.md
  content/sensu-core/1.3/overview/_index.md
  content/sensu-core/1.3/platforms/_index.md
  content/sensu-core/1.3/quick-start/_index.md
  content/sensu-core/1.3/reference/_index.md
Labels: ready-for-review

#358 Adding PR & issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, ready-for-review

#363 Updating frontmatter in indexes
  content/sensu-core/0.29/guides/_index.md
  content/sensu-core/0.29/installation/_index.md
  content/sensu-core/0.29/overview/_index.md
  content/sensu-core/0.29/platforms/_index.md
  content/sensu-core/1.0/guides/_index.md
  content/sensu-core/1.0/installation/_index.md
  content/sensu-core/1.0/overview/_index.md
  content/sensu-core/1.0/platforms/_index.md
  content/sensu-core/1.1/guides/_index.md
  content/sensu-core/1.1/installation/_index.md
  content/sensu-core/1.1/overview/_index.md
  content/sensu-core/1.1/platforms/_index.md
  content/sensu-core/1.2/guides/_index.md
  content/sensu-core/1.2/installation/_index.md
  content/sensu-core/1.2/overview/_index.md
  content/sensu-core/1.2/platforms/_index.md
  content/sensu-core/1.3/guides/_index.md
  content/sensu-core/1.3/installation/_index.md
  content/sensu-core/1.3/overview/_index.md
  content/sensu-core/1.3/platforms/_index.md
Labels: ready-for-review

#361 Added reference doc for tokens
  content/sensu-core/2.0/reference/checks.md
  content/sensu-core/2.0/reference/entities.md
  content/sensu-core/2.0/reference/tokens.md
Labels: ready-for-review

#348 Dismissible & customizable alert banner
  layouts/_default/single.html
  layouts/partials/alert.html
  layouts/partials/alertSection.html
  layouts/partials/header.html
  layouts/shortcodes/alert.html
  static/stylesheets/override.css
Labels: ready-for-review

#366 Add check subdues guide
  content/sensu-core/2.0/guides/schedule-checks.md
Labels: ready-for-review

#369 Add when attribute specs for filters
  content/sensu-core/2.0/reference/filters.md
Labels: ready-for-review

#307 Allow platforms override per page
  config.toml
  content/sensu-core/2.0/getting-started/installation-and-configuration.md
  layouts/_default/single.html
  layouts/partials/platformDropdown.html
  static/js/platformDropdowns.js
Labels: enhancement, ready-for-review

#376 update enterprise overview pages with link to core install guide
  content/sensu-enterprise/2.6/_index.md
  content/sensu-enterprise/2.7/_index.md
  content/sensu-enterprise/2.8/_index.md
Labels: ready-for-review

#318 Securing Sensu Guide
  content/sensu-core/0.29/guides/securing-sensu.md
  content/sensu-core/1.0/guides/securing-sensu.md
  content/sensu-core/1.1/guides/securing-sensu.md
  content/sensu-core/1.2/guides/securing-sensu.md
  content/sensu-core/1.3/guides/securing-sensu.md
Labels: ready-for-review

#372 Add hardware recommendation guide.
  content/sensu-core/2.0/getting-started/recommended-hardware.md
Labels: ready-for-review
