Repository sensu/sensu-docs, pull requests merged in 2018-05, with the labels that each got.

#387 Fix typo with high_flap_threshold attribute in checks reference
  content/sensu-core/2.0/reference/checks.md
Labels: ready-for-review

#379 Zombie warning!
  content/sensu-core/2.0/guides/monitor-server-resources.md
Labels: ready-for-review

#371 Guide on how to populate influxdb metrics using handlers
  content/sensu-core/2.0/guides/influx-db-metric-handler.md
Labels: ready-for-review

#370 Guide on how to aggregate metrics with the statsd listener
  content/sensu-core/2.0/guides/aggregate-metrics-statsd.md
Labels: ready-for-review

#403 Check output metric extraction field names should be more specific
  content/sensu-core/2.0/guides/extract-metrics-with-checks.md
  content/sensu-core/2.0/guides/influx-db-metric-handler.md
Labels: ready-for-review

#398 Minor typo: socker -> socket
  content/sensu-core/2.0/reference/handlers.md
Labels: ready-for-review

#397 Fix example of `round_robin` checks in sensu 2.0
  content/sensu-core/2.0/reference/checks.md
Labels: ready-for-review

#389 Guides review
  content/sensu-core/2.0/guides/create-read-only-user.md
  content/sensu-core/2.0/guides/install-check-executables-with-assets.md
  content/sensu-core/2.0/guides/plan-maintenance.md
  content/sensu-core/2.0/guides/reduce-alert-fatigue.md
Labels: ready-for-review

#405 Clarification around not_silenced built-in filter
  content/sensu-core/2.0/guides/plan-maintenance.md
  content/sensu-core/2.0/guides/send-slack-alerts.md
  content/sensu-core/2.0/reference/silencing.md
Labels: ready-for-review

#412 Document different types of events and event polymorphism
  content/sensu-core/2.0/reference/checks.md
  content/sensu-core/2.0/reference/events.md
Labels: ready-for-review

#413 Correct custom attribute name
  content/sensu-core/2.0/reference/sensu-query-expressions.md
Labels: ready-for-review

#394 remove Ubuntu and Debian references in RHEL platform text
  content/sensu-core/0.29/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.0/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.1/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.2/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.3/platforms/sensu-on-rhel-centos.md
Labels: ready-for-review

#418 Replacing non-existent "recurrences" filter with "occurrences" in han…
  content/sensu-core/0.29/reference/handlers.md
  content/sensu-core/1.0/reference/handlers.md
  content/sensu-core/1.1/reference/handlers.md
  content/sensu-core/1.2/reference/handlers.md
  content/sensu-core/1.3/reference/handlers.md
  content/sensu-core/1.4/reference/handlers.md
  content/sensu-core/2.0/reference/handlers.md
Labels: ready-for-review

#422 Removed index
  content/sensu-enterprise/2.6/rbac/_index.md
Labels: ready-for-review

#416 Fixes #115 and links to Graphite docs
  content/sensu-core/0.29/guides/intro-to-checks.md
  content/sensu-core/1.0/guides/intro-to-checks.md
  content/sensu-core/1.1/guides/intro-to-checks.md
  content/sensu-core/1.2/guides/intro-to-checks.md
  content/sensu-core/1.3/guides/intro-to-checks.md
  content/sensu-core/1.4/guides/intro-to-checks.md
Labels: in progress

#377 add rollbar integration to enterprise built-in-handlers list
  content/sensu-enterprise/2.6/built-in-handlers.md
  content/sensu-enterprise/2.7/built-in-handlers.md
  content/sensu-enterprise/2.8/built-in-handlers.md
Labels: ready-for-review

#415 Fixes #122 and updates check reference doc
  content/sensu-core/0.29/reference/checks.md
  content/sensu-core/0.29/reference/clients.md
  content/sensu-core/1.0/reference/checks.md
  content/sensu-core/1.0/reference/clients.md
  content/sensu-core/1.1/reference/checks.md
  content/sensu-core/1.1/reference/clients.md
  content/sensu-core/1.2/reference/checks.md
  content/sensu-core/1.2/reference/clients.md
  content/sensu-core/1.3/reference/checks.md
  content/sensu-core/1.3/reference/clients.md
  content/sensu-core/1.4/reference/checks.md
  content/sensu-core/1.4/reference/clients.md
Labels: in progress

#375 Updating occurrence examples to avoid confusion
  content/sensu-core/0.29/reference/filters.md
  content/sensu-core/1.0/reference/filters.md
  content/sensu-core/1.1/reference/filters.md
  content/sensu-core/1.2/reference/filters.md
  content/sensu-core/1.3/reference/filters.md
Labels: errata, in progress

#382 Add hyphen to front matter to avoid nav rendering.
  content/sensu-core/0.29/quick-start/_index.md
  content/sensu-core/1.0/quick-start/_index.md
  content/sensu-core/1.1/quick-start/_index.md
  content/sensu-core/1.2/quick-start/_index.md
  content/sensu-core/1.3/quick-start/_index.md
Labels: ready-for-review

#373 Moves check attribute references from plugins reference to checks refernce
  content/plugins/2.3/reference.md
  content/sensu-core/0.29/reference/checks.md
  content/sensu-core/1.0/reference/checks.md
  content/sensu-core/1.1/reference/checks.md
  content/sensu-core/1.2/reference/checks.md
  content/sensu-core/1.3/reference/checks.md
Labels: in progress

#428 Blockquote Styling Update
  static/stylesheets/docs-overrides.css
Labels: ready-for-review

#400 Fix broken link in Learn Sensu in 15 Minutes
  content/sensu-core/0.29/quick-start/learn-sensu-basics.md
  content/sensu-core/1.0/quick-start/learn-sensu-basics.md
  content/sensu-core/1.1/quick-start/learn-sensu-basics.md
  content/sensu-core/1.2/quick-start/learn-sensu-basics.md
  content/sensu-core/1.3/quick-start/learn-sensu-basics.md
  content/sensu-core/1.4/quick-start/learn-sensu-basics.md
Labels: ready-for-review

#432 Fix numbering and links in quick install guide
  content/sensu-core/0.29/quick-start/five-minute-install.md
  content/sensu-core/1.0/quick-start/five-minute-install.md
  content/sensu-core/1.1/quick-start/five-minute-install.md
  content/sensu-core/1.2/quick-start/five-minute-install.md
  content/sensu-core/1.3/quick-start/five-minute-install.md
  content/sensu-core/1.4/quick-start/five-minute-install.md
Labels: ready-for-review

#421 Updates to new location of the influxdb handler
  content/sensu-core/2.0/guides/influx-db-metric-handler.md
Labels: ready-for-review

#436 Document configurable log levels
  content/sensu-core/2.0/getting-started/installation-and-configuration.md
Labels: ready-for-review

#434 Fix errors when running locally
  content/sensu-core/0.29/guides/overview.md
  content/sensu-core/0.29/overview/platforms.md
  content/sensu-core/1.0/guides/overview.md
  content/sensu-core/1.0/overview/platforms.md
  content/sensu-core/1.1/guides/overview.md
  content/sensu-core/1.1/overview/platforms.md
  content/sensu-core/1.2/guides/overview.md
  content/sensu-core/1.2/overview/platforms.md
  content/sensu-core/1.3/guides/overview.md
  content/sensu-core/1.3/overview/platforms.md
  content/sensu-core/1.4/guides/overview.md
  content/sensu-core/1.4/overview/platforms.md
Labels: ready-for-review
