Repository sensu/sensu-docs, pull requests merged in 2018-02, with the labels that each got.

#179 Updating multiple doc revs
  CONTRIBUTING.md
Labels: in progress, ready-for-review

#180 Move chunks of Heroku and Hugo content to the Wiki
  README.md
Labels: in progress

#182 Gruntfile.js: processFile sends non-markdown to processMDFile
  Gruntfile.js
  static/js/lunr/PagesIndex.json
Labels: in progress, ready-for-review

#183 Further automate and document the build process
  .travis.yml
  CONTRIBUTING.md
  Gruntfile.js
  README.md
  package.json
  yarn.lock
Labels: in progress

#184 Changing the index.md layout to `single` temporarily to avoid issues with broken links from the the platform selector.
  content/sensu-core/0.29/_index.md
  content/sensu-core/1.0/_index.md
  content/sensu-core/1.1/_index.md
  content/sensu-core/1.2/_index.md
Labels: in progress

#181 Creating a doc template for community members to use
  static/files/sensu-doc-template.md
Labels: in progress

#171 Add getting started section to 2.0 docs
  config.toml
  content/sensu-core/2.0/_index.md
  content/sensu-core/2.0/getting-started/configuring-sensuctl.md
  content/sensu-core/2.0/getting-started/installation-and-configuration.md
Labels: ready-for-review

#192 Create references and port events
  content/sensu-core/2.0/reference/events.md
Labels: in progress, ready-for-review

#188 Update contributing
  CONTRIBUTING.md
Labels: in progress, ready-for-review

#206 Adding troubleshooting to README
  README.md
Labels: in progress

#210 Couple of typos
  README.md
Labels: ready-for-review

#211 Couple of typos
  README.md
Labels: in progress

#191 Added Overview section and checks documentation
  content/sensu-core/2.0/overview/checks.md
  static/images/sensuctl-check-create.gif
Labels: in progress

#212 Package links now point to public repos.
  content/sensu-core/2.0/getting-started/configuring-sensuctl.md
  content/sensu-core/2.0/getting-started/installation-and-configuration.md
Labels: in progress, ready-for-review

#209 Added Silencing overview guide.
  content/sensu-core/2.0/overview/silencing.md
Labels: in progress, ready-for-review

#193 Port hooks reference guide
  content/sensu-core/2.0/reference/hooks.md
Labels: in progress, ready-for-review

#207 Port rbac reference guide
  content/sensu-core/2.0/reference/rbac.md
  images/rbac.png
Labels: in progress

#218 Grunt hugo-build command should fail if hugo fails
  Gruntfile.js
  static/js/lunr/PagesIndex.json
Labels: ready-for-review

#222 [sensu-core] use single layout for 2.0 index page
  content/sensu-core/2.0/_index.md
Labels: in progress

#219 update baseurl to use sensuapp.org domain
  config.toml
Labels: ready-for-review

#224 Added severities & filters. Fixes #220
  content/sensu-enterprise/2.6/integrations/chef.md
  content/sensu-enterprise/2.6/integrations/datadog.md
  content/sensu-enterprise/2.6/integrations/ec2.md
  content/sensu-enterprise/2.6/integrations/email.md
  content/sensu-enterprise/2.6/integrations/hipchat.md
  content/sensu-enterprise/2.6/integrations/irc.md
  content/sensu-enterprise/2.6/integrations/jira.md
  content/sensu-enterprise/2.6/integrations/opsgenie.md
  content/sensu-enterprise/2.6/integrations/pagerduty.md
  content/sensu-enterprise/2.6/integrations/rollbar.md
  content/sensu-enterprise/2.6/integrations/servicenow.md
  content/sensu-enterprise/2.6/integrations/slack.md
  content/sensu-enterprise/2.6/integrations/snmp.md
  content/sensu-enterprise/2.6/integrations/victorops.md
  content/sensu-enterprise/2.7/integrations/chef.md
  content/sensu-enterprise/2.7/integrations/datadog.md
  content/sensu-enterprise/2.7/integrations/ec2.md
  content/sensu-enterprise/2.7/integrations/email.md
  content/sensu-enterprise/2.7/integrations/hipchat.md
  content/sensu-enterprise/2.7/integrations/irc.md
  content/sensu-enterprise/2.7/integrations/jira.md
  content/sensu-enterprise/2.7/integrations/opsgenie.md
  content/sensu-enterprise/2.7/integrations/pagerduty.md
  content/sensu-enterprise/2.7/integrations/rollbar.md
  content/sensu-enterprise/2.7/integrations/servicenow.md
  content/sensu-enterprise/2.7/integrations/slack.md
  content/sensu-enterprise/2.7/integrations/snmp.md
  content/sensu-enterprise/2.7/integrations/victorops.md
  content/sensu-enterprise/2.8/integrations/chef.md
  content/sensu-enterprise/2.8/integrations/datadog.md
  content/sensu-enterprise/2.8/integrations/ec2.md
  content/sensu-enterprise/2.8/integrations/email.md
  content/sensu-enterprise/2.8/integrations/hipchat.md
  content/sensu-enterprise/2.8/integrations/irc.md
  content/sensu-enterprise/2.8/integrations/jira.md
  content/sensu-enterprise/2.8/integrations/opsgenie.md
  content/sensu-enterprise/2.8/integrations/pagerduty.md
  content/sensu-enterprise/2.8/integrations/rollbar.md
  content/sensu-enterprise/2.8/integrations/servicenow.md
  content/sensu-enterprise/2.8/integrations/slack.md
  content/sensu-enterprise/2.8/integrations/snmp.md
  content/sensu-enterprise/2.8/integrations/victorops.md
Labels: in progress

#225 Fix live reload by including footer_js partial
  layouts/_default/single.html
Labels: in progress
