Repository sensu/sensu-docs, pull requests merged in 2018-11, with the labels that each got.

#824 Add agent reference
  content/sensu-core/2.0/reference/agent.md
Labels: ready-for-review

#855 Clarify behavior of Silenced API /clear endpoint
  content/sensu-core/0.29/api/silenced.md
  content/sensu-core/1.0/api/silenced.md
  content/sensu-core/1.1/api/silenced.md
  content/sensu-core/1.2/api/silenced.md
  content/sensu-core/1.3/api/silenced.md
  content/sensu-core/1.4/api/silenced.md
  content/sensu-core/1.5/api/silenced.md
  content/sensu-core/1.6/api/silenced.md
Labels: ready-for-review

#861 Adding ec2 account attributes to the client reference
  content/sensu-core/0.29/reference/clients.md
  content/sensu-core/1.0/reference/clients.md
  content/sensu-core/1.1/reference/clients.md
  content/sensu-core/1.2/reference/clients.md
  content/sensu-core/1.3/reference/clients.md
  content/sensu-core/1.4/reference/clients.md
  content/sensu-core/1.5/reference/clients.md
  content/sensu-core/1.6/reference/clients.md
Labels: in progress

#870 Document the keepalive handler
  content/sensu-core/2.0/reference/agent.md
Labels: ready-for-review

#880 Create pre-release version 3.3 for Sensu Enterprise
  config.toml
  content/sensu-enterprise/3.3/_index.md
  content/sensu-enterprise/3.3/api.md
  content/sensu-enterprise/3.3/built-in-filters.md
  content/sensu-enterprise/3.3/built-in-handlers.md
  content/sensu-enterprise/3.3/built-in-mutators.md
  content/sensu-enterprise/3.3/changelog.md
  content/sensu-enterprise/3.3/configuration.md
  content/sensu-enterprise/3.3/contact-routing.md
  content/sensu-enterprise/3.3/files/RFC-1212-MIB.txt
  content/sensu-enterprise/3.3/files/RFC-1215-MIB.txt
  content/sensu-enterprise/3.3/files/SENSU-ENTERPRISE-NOTIFY-MIB.txt
  content/sensu-enterprise/3.3/files/SENSU-ENTERPRISE-ROOT-MIB.txt
  content/sensu-enterprise/3.3/files/SENSU-ENTERPRISE-V1-MIB.txt
  content/sensu-enterprise/3.3/files/cross-account-assumerole-policy.json
  content/sensu-enterprise/3.3/files/cross-account-assumerole-role.json
  content/sensu-enterprise/3.3/files/cross-account-readonly-policy.json
  content/sensu-enterprise/3.3/files/cross-account-readonly-role.json
  content/sensu-enterprise/3.3/files/sensu-ec2-iam-policy.json
  content/sensu-enterprise/3.3/files/sensu-ec2-iam-role.json
  content/sensu-enterprise/3.3/filters/_index.md
  content/sensu-enterprise/3.3/filters/check-dependencies.md
  content/sensu-enterprise/3.3/filters/handle-when.md
  content/sensu-enterprise/3.3/filters/silence-stashes.md
  content/sensu-enterprise/3.3/guides/_index.md
  content/sensu-enterprise/3.3/guides/troubleshooting.md
  content/sensu-enterprise/3.3/guides/using-ec2.md
  content/sensu-enterprise/3.3/guides/using-snow.md
  content/sensu-enterprise/3.3/installation/_index.md
  content/sensu-enterprise/3.3/installation/overview.md
  content/sensu-enterprise/3.3/installation/testing-prereleases.md
  content/sensu-enterprise/3.3/integrations/_index.md
  content/sensu-enterprise/3.3/integrations/chef.md
  content/sensu-enterprise/3.3/integrations/datadog.md
  content/sensu-enterprise/3.3/integrations/ec2.md
  content/sensu-enterprise/3.3/integrations/email.md
  content/sensu-enterprise/3.3/integrations/event_stream.md
  content/sensu-enterprise/3.3/integrations/flapjack.md
  content/sensu-enterprise/3.3/integrations/graphite.md
  content/sensu-enterprise/3.3/integrations/graylog.md
  content/sensu-enterprise/3.3/integrations/hipchat.md
  content/sensu-enterprise/3.3/integrations/influxdb.md
  content/sensu-enterprise/3.3/integrations/irc.md
  content/sensu-enterprise/3.3/integrations/jira.md
  content/sensu-enterprise/3.3/integrations/librato.md
  content/sensu-enterprise/3.3/integrations/opentsdb.md
  content/sensu-enterprise/3.3/integrations/opsgenie.md
  content/sensu-enterprise/3.3/integrations/pagerduty.md
  content/sensu-enterprise/3.3/integrations/puppet.md
  content/sensu-enterprise/3.3/integrations/rollbar.md
  content/sensu-enterprise/3.3/integrations/servicenow.md
  content/sensu-enterprise/3.3/integrations/slack.md
  content/sensu-enterprise/3.3/integrations/snmp.md
  content/sensu-enterprise/3.3/integrations/timescaledb.md
  content/sensu-enterprise/3.3/integrations/victorops.md
  content/sensu-enterprise/3.3/integrations/wavefront.md
  content/sensu-enterprise/3.3/quick-start/_index.md
  content/sensu-enterprise/3.3/quick-start/five-minute-install.md
  content/sensu-enterprise/3.3/quick-start/get-started.md
  content/sensu-enterprise/3.3/upgrading.md
Labels: 1.x, ready-for-review

#886 [WIP] Promote Sensu Enterprise 3.3 to latest
  config.toml
  content/sensu-enterprise/3.3/changelog.md
  static.json
Labels: 1.x, in progress

#883 Assorted fixups
  CONTRIBUTING.md
  README.md
  content/sensu-core/0.29/reference/clients.md
  content/sensu-core/1.0/reference/clients.md
  content/sensu-core/1.1/reference/clients.md
  content/sensu-core/1.2/reference/clients.md
  content/sensu-core/1.3/reference/clients.md
  content/sensu-core/1.4/reference/clients.md
  content/sensu-core/1.5/reference/clients.md
  content/sensu-core/1.6/reference/clients.md
  content/sensu-go/5.0/guides/install-check-executables-with-assets.md
Labels: in progress

#898 Update documentation for javascript filtering.
  content/sensu-go/5.0/reference/assets.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.0/reference/sensu-query-expressions.md
Labels: in progress

#896 Document built-in filters in Sensu Go
  content/sensu-go/5.0/reference/filters.md
Labels: 5.x, in progress

#905 Fix example highlight for user
  content/sensu-enterprise-dashboard/2.10/configuration.md
  content/sensu-enterprise-dashboard/2.11/configuration.md
  content/sensu-enterprise-dashboard/2.12/configuration.md
  content/sensu-enterprise-dashboard/2.9/configuration.md
Labels: ready-for-review

#909 Use an array to configure agent subscriptions
  content/sensu-go/5.0/guides/monitor-external-resources.md
  content/sensu-go/5.0/reference/agent.md
Labels: ready-for-review

#890 Update RBAC docs for Sensu Go
  content/sensu-go/5.0/dashboard/overview.md
  content/sensu-go/5.0/getting-started/glossary.md
  content/sensu-go/5.0/guides/create-read-only-user.md
  content/sensu-go/5.0/guides/install-check-executables-with-assets.md
  content/sensu-go/5.0/guides/run-auto-remediation.md
  content/sensu-go/5.0/installation/install-sensu.md
  content/sensu-go/5.0/reference/agent.md
  content/sensu-go/5.0/reference/assets.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/entities.md
  content/sensu-go/5.0/reference/events.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.0/reference/hooks.md
  content/sensu-go/5.0/reference/mutators.md
  content/sensu-go/5.0/reference/rbac.md
  content/sensu-go/5.0/reference/sensu-query-expressions.md
  content/sensu-go/5.0/reference/silencing.md
  content/sensu-go/5.0/reference/tokens.md
  content/sensu-go/5.0/sensuctl/reference.md
Labels: 5.x, ready-for-review

#910 Small typo in ToC
  content/plugins/1.0/reference.md
Labels: ready-for-review

#915 Remove instructions for nightly releases
  content/sensu-go/5.0/getting-started/glossary.md
  content/sensu-go/5.0/guides/reduce-alert-fatigue.md
  content/sensu-go/5.0/installation/install-sensu.md
  content/sensu-go/5.0/installation/testing-nightly-releases.md
  content/sensu-go/5.0/reference/agent.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/entities.md
  content/sensu-go/5.0/reference/events.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.0/reference/hooks.md
  content/sensu-go/5.0/reference/mutators.md
  content/sensu-go/5.0/reference/tokens.md
  content/sensu-go/5.0/sensuctl/reference.md
Labels: in progress

#914 Breaking up the wall of text
  content/plugins/1.0/developer-guidelines.md
Labels: in progress

#860 Guide for performing end to end troubleshooting
  content/sensu-core/0.29/guides/troubleshooting.md
  content/sensu-core/1.0/guides/troubleshooting.md
  content/sensu-core/1.1/guides/troubleshooting.md
  content/sensu-core/1.2/guides/troubleshooting.md
  content/sensu-core/1.3/guides/troubleshooting.md
  content/sensu-core/1.4/guides/troubleshooting.md
  content/sensu-core/1.5/guides/troubleshooting.md
  content/sensu-core/1.6/guides/troubleshooting.md
Labels: ready-for-review

#920 Remove check subdues and when attributes
  content/sensu-go/5.0/getting-started/glossary.md
  content/sensu-go/5.0/guides/schedule-checks.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/events.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.0/reference/tokens.md
  content/sensu-go/5.0/sensuctl/reference.md
Labels: in progress

#918 Add Sensu Go config mgmt and media pages
  content/sensu-go/5.0/getting-started/media.md
  content/sensu-go/5.0/installation/configuration-management.md
Labels: ready-for-review

#919 Include asset format info in guide
  content/sensu-go/5.0/guides/install-check-executables-with-assets.md
Labels: ready-for-review

#921 Document sensuctl edit, clarify sensuctl create
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.0/sensuctl/reference.md
Labels: ready-for-review

#924 Correct docs for check hooks
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/hooks.md
Labels: in progress

#929 Update entity_class spec to reflect current state
  content/sensu-go/5.0/reference/entities.md
Labels: ready-for-review

#884 Sensu Go cluster configuration guide update
  content/sensu-go/5.0/guides/clustering.md
  content/sensu-go/5.0/installation/install-sensu.md
  content/sensu-go/5.0/reference/backend.md
Labels: ready-for-review

#927 Specify the RBAC requirements for --all-namespaces
  content/sensu-go/5.0/reference/rbac.md
Labels: ready-for-review

#930 Update sensuctl reference
  content/sensu-go/5.0/installation/install-sensu.md
  content/sensu-go/5.0/sensuctl/reference.md
Labels: ready-for-review

#943 Add metadata wrapper for Sensu Go types
  content/sensu-go/5.0/reference/assets.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/entities.md
  content/sensu-go/5.0/reference/events.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.0/reference/hooks.md
  content/sensu-go/5.0/reference/mutators.md
  content/sensu-go/5.0/reference/silencing.md
  content/sensu-go/5.0/reference/tokens.md
Labels: in progress

#950 Remove extensions from Sensu Go docs
  content/sensu-go/5.0/api/extensions.md
  content/sensu-go/5.0/reference/rbac.md
  content/sensu-go/5.0/sensuctl/reference.md
Labels: in progress

#948 Remove round robin from Sensu Go docs
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/events.md
  content/sensu-go/5.0/reference/tokens.md
Labels: in progress

#955 Typo
  content/sensu-go/5.0/api/overview.md
Labels: in progress

#942 Grammar correction in a sentence
  content/sensu-core/1.6/overview/platforms.md
Labels: ready-for-review

#926 Securing Sensu Go
  content/sensu-go/5.0/guides/securing-sensu.md
Labels: in progress

#956 Copying 942 changes to older versions
  content/sensu-core/0.29/overview/platforms.md
  content/sensu-core/1.0/overview/platforms.md
  content/sensu-core/1.1/overview/platforms.md
  content/sensu-core/1.2/overview/platforms.md
  content/sensu-core/1.3/overview/platforms.md
  content/sensu-core/1.4/overview/platforms.md
  content/sensu-core/1.5/overview/platforms.md
Labels: in progress

#962 Sensu Go errata fixes
  content/sensu-go/5.0/getting-started/glossary.md
  content/sensu-go/5.0/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.0/guides/extract-metrics-with-checks.md
  content/sensu-go/5.0/guides/influx-db-metric-handler.md
  content/sensu-go/5.0/guides/monitor-external-resources.md
  content/sensu-go/5.0/guides/reduce-alert-fatigue.md
  content/sensu-go/5.0/guides/securing-sensu.md
  content/sensu-go/5.0/reference/agent.md
  content/sensu-go/5.0/reference/assets.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.0/reference/rbac.md
  content/sensu-go/5.0/reference/tokens.md
  content/sensu-go/5.0/sensuctl/reference.md
Labels: in progress

#957 Add PUT and POST requests to Sensu Go API docs
  content/sensu-go/5.0/api/assets.md
  content/sensu-go/5.0/api/checks.md
  content/sensu-go/5.0/api/cluster-role-bindings.md
  content/sensu-go/5.0/api/cluster-roles.md
  content/sensu-go/5.0/api/entities.md
  content/sensu-go/5.0/api/events.md
  content/sensu-go/5.0/api/filters.md
  content/sensu-go/5.0/api/handlers.md
  content/sensu-go/5.0/api/hooks.md
  content/sensu-go/5.0/api/mutators.md
  content/sensu-go/5.0/api/namespaces.md
  content/sensu-go/5.0/api/role-bindings.md
  content/sensu-go/5.0/api/roles.md
  content/sensu-go/5.0/api/silenced.md
  content/sensu-go/5.0/api/users.md
Labels: ready-for-review

#953 Add upgrade guide for Sensu Go
  content/sensu-go/5.0/installation/recommended-hardware.md
  content/sensu-go/5.0/installation/upgrade.md
Labels: in progress

#960 Add install plugins guide for Sensu Go
  content/sensu-go/5.0/installation/plugins.md
Labels: ready-for-review

#949 Rewrite Go Hooks guide
  content/sensu-go/5.0/guides/enrich-events-with-hooks.md
  content/sensu-go/5.0/guides/run-auto-remediation.md
  content/sensu-go/5.0/reference/hooks.md
Labels: in progress

#965 Fix Sensu Go PUT endpoints, add DELETE endpoints
  content/sensu-go/5.0/api/assets.md
  content/sensu-go/5.0/api/checks.md
  content/sensu-go/5.0/api/cluster-role-bindings.md
  content/sensu-go/5.0/api/cluster-roles.md
  content/sensu-go/5.0/api/entities.md
  content/sensu-go/5.0/api/filters.md
  content/sensu-go/5.0/api/handlers.md
  content/sensu-go/5.0/api/hooks.md
  content/sensu-go/5.0/api/mutators.md
  content/sensu-go/5.0/api/namespaces.md
  content/sensu-go/5.0/api/role-bindings.md
  content/sensu-go/5.0/api/roles.md
  content/sensu-go/5.0/api/silenced.md
  content/sensu-go/5.0/api/users.md
Labels: 5.x, ready-for-review
