Repository sensu/sensu-docs, pull requests merged in 2018-06, with the labels that each got.

#431 Document sensuctl create
  content/sensu-core/2.0/getting-started/configuring-sensuctl.md
Labels: 2.x, ready-for-review

#443 Upgrade supported versions of RabbitMQ and Erlang
  content/sensu-core/0.29/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/0.29/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/0.29/installation/install-rabbitmq.md
  content/sensu-core/0.29/reference/rabbitmq.md
  content/sensu-core/1.0/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.0/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.0/installation/install-rabbitmq.md
  content/sensu-core/1.0/reference/rabbitmq.md
  content/sensu-core/1.1/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.1/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.1/installation/install-rabbitmq.md
  content/sensu-core/1.1/reference/rabbitmq.md
  content/sensu-core/1.2/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.2/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.2/installation/install-rabbitmq.md
  content/sensu-core/1.2/reference/rabbitmq.md
  content/sensu-core/1.3/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.3/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.3/installation/install-rabbitmq.md
  content/sensu-core/1.3/reference/rabbitmq.md
  content/sensu-core/1.4/installation/install-rabbitmq-on-rhel-centos.md
  content/sensu-core/1.4/installation/install-rabbitmq-on-ubuntu-debian.md
  content/sensu-core/1.4/installation/install-rabbitmq.md
  content/sensu-core/1.4/reference/rabbitmq.md
Labels: ready-for-review

#455 Update core 1.4 changelog for 1.4.2 release
  content/sensu-core/1.4/changelog.md
Labels: ready-for-review

#463 Filters to Filter
  content/sensu-core/0.29/guides/intro-to-filters.md
  content/sensu-core/0.29/reference/filters.md
  content/sensu-core/0.29/reference/server.md
  content/sensu-core/1.0/guides/intro-to-filters.md
  content/sensu-core/1.0/reference/filters.md
  content/sensu-core/1.0/reference/handlers.md
  content/sensu-core/1.0/reference/server.md
  content/sensu-core/1.1/guides/intro-to-filters.md
  content/sensu-core/1.1/reference/filters.md
  content/sensu-core/1.1/reference/server.md
  content/sensu-core/1.2/guides/intro-to-filters.md
  content/sensu-core/1.2/reference/filters.md
  content/sensu-core/1.2/reference/server.md
  content/sensu-core/1.3/guides/intro-to-filters.md
  content/sensu-core/1.3/reference/filters.md
  content/sensu-core/2.0/reference/filters.md
  content/sensu-core/2.0/reference/handlers.md
  content/sensu-enterprise/2.6/filters/handle-when.md
  content/sensu-enterprise/2.6/filters/silence-stashes.md
  content/sensu-enterprise/2.7/filters/check-dependencies.md
  content/sensu-enterprise/2.7/filters/silence-stashes.md
  content/sensu-enterprise/2.8/filters/check-dependencies.md
  content/sensu-enterprise/2.8/filters/handle-when.md
  content/sensu-enterprise/2.8/filters/silence-stashes.md
Labels: ready-for-review

#471 Fix invalid example json
  content/sensu-core/2.0/reference/tokens.md
Labels: ready-for-review

#466 add Upgrading Sensu Enterprise pages
  content/sensu-enterprise/2.6/upgrading.md
  content/sensu-enterprise/2.7/upgrading.md
  content/sensu-enterprise/2.8/upgrading.md
  content/sensu-enterprise/3.0/upgrading.md
Labels: ready-for-review

#461 Sensu Enterprise 3.0 OpsGenie changes
  content/sensu-enterprise/3.0/integrations/opsgenie.md
Labels: ready-for-review

#327 Securing RabbitMQ Guide
  content/sensu-core/0.29/guides/securing-rabbitmq.md
  content/sensu-core/0.29/guides/securing-sensu.md
  content/sensu-core/1.0/guides/securing-rabbitmq.md
  content/sensu-core/1.0/guides/securing-sensu.md
  content/sensu-core/1.1/guides/securing-rabbitmq.md
  content/sensu-core/1.1/guides/securing-sensu.md
  content/sensu-core/1.2/guides/securing-rabbitmq.md
  content/sensu-core/1.2/guides/securing-sensu.md
  content/sensu-core/1.3/guides/securing-rabbitmq.md
  content/sensu-core/1.3/guides/securing-sensu.md
  content/sensu-core/1.4/guides/securing-rabbitmq.md
  content/sensu-core/1.4/guides/securing-sensu.md
  static/images/sensu-amqp-entities.png
Labels: ready-for-review

#464 Fix CSS list and table spacing bugs
  static/stylesheets/docs-overrides.css
  static/stylesheets/override.css
Labels: ready-for-review

#476 Fix frontmatter in securing rabbitmq guide
  content/sensu-core/0.29/guides/securing-rabbitmq.md
  content/sensu-core/1.0/guides/securing-rabbitmq.md
  content/sensu-core/1.1/guides/securing-rabbitmq.md
  content/sensu-core/1.2/guides/securing-rabbitmq.md
  content/sensu-core/1.3/guides/securing-rabbitmq.md
  content/sensu-core/1.4/guides/securing-rabbitmq.md
Labels: ready-for-review

#478 Fix links
  content/sensu-core/0.29/_index.md
  content/sensu-core/1.0/_index.md
  content/sensu-core/1.1/_index.md
  content/sensu-core/1.2/_index.md
  content/sensu-core/1.3/_index.md
  content/sensu-core/1.4/_index.md
Labels: ready-for-review

#477 Add api-only mode to Sensu Enterprise
  content/sensu-enterprise/3.0/configuration.md
Labels: ready-for-review

#482 add EPEL note for installing Enterprise 3.0 on RHEL/Centos 6
  content/sensu-core/0.29/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.0/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.1/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.2/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.3/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.4/platforms/sensu-on-rhel-centos.md
Labels: ready-for-review

#467 Enterprise 3.0 changelog
  content/sensu-enterprise/2.6/changelog.md
  content/sensu-enterprise/2.7/changelog.md
  content/sensu-enterprise/2.8/changelog.md
  content/sensu-enterprise/3.0/changelog.md
Labels: ready-for-review

#486 Promote Sensu Enterprise 3.0
  config.toml
  static.json
Labels: ready-for-review

#491 Fixes #430
  content/sensu-core/0.29/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.0/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.1/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.2/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.3/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.4/platforms/sensu-on-ibm-aix.md
Labels: ready-for-review

#481 Fixed quotes so the command is copy-pasteable.
  content/sensu-core/2.0/guides/influx-db-metric-handler.md
Labels: ready-for-review

#493 Use best practices in check hooks reference docs
  content/sensu-core/1.1/reference/checks.md
  content/sensu-core/1.2/reference/checks.md
  content/sensu-core/1.3/reference/checks.md
  content/sensu-core/1.4/reference/checks.md
Labels: ready-for-review

#499 Updating FAQ w/ release matrix per #119
  content/sensu-core/0.29/faq.md
  content/sensu-core/1.0/faq.md
  content/sensu-core/1.1/faq.md
  content/sensu-core/1.2/faq.md
  content/sensu-core/1.3/faq.md
  content/sensu-core/1.4/faq.md
Labels: ready-for-review

#494 add security fix note to core 1.4.2 changelog
  content/sensu-core/1.4/changelog.md
Labels: ready-for-review

#497 Added handler info for keepalives
  content/sensu-core/0.29/reference/handlers.md
  content/sensu-core/1.0/reference/handlers.md
  content/sensu-core/1.1/reference/handlers.md
  content/sensu-core/1.2/reference/handlers.md
  content/sensu-core/1.3/reference/handlers.md
  content/sensu-core/1.4/reference/handlers.md
Labels: ready-for-review

#505 Fix SSL tarball in Sensu Core 1.4 docs
  content/sensu-core/1.4/files/sensu_ssl_tool.tar
Labels: ready-for-review

#503 Adds uchiwa config
  content/sensu-core/0.29/quick-start/five-minute-install.md
  content/sensu-core/1.0/quick-start/five-minute-install.md
  content/sensu-core/1.1/quick-start/five-minute-install.md
  content/sensu-core/1.2/quick-start/five-minute-install.md
  content/sensu-core/1.3/quick-start/five-minute-install.md
  content/sensu-core/1.4/quick-start/five-minute-install.md
Labels: ready-for-review

#502 Removed overview content
  content/sensu-enterprise-dashboard/2.10/dashboard.md
  content/sensu-enterprise-dashboard/2.11/dashboard.md
  content/sensu-enterprise-dashboard/2.9/dashboard.md
Labels: ready-for-review

#504 Adds "Pro Tip" for hexdigest to health api doc
  content/sensu-core/0.29/api/health-and-info.md
  content/sensu-core/1.0/api/health-and-info.md
  content/sensu-core/1.1/api/health-and-info.md
  content/sensu-core/1.2/api/health-and-info.md
  content/sensu-core/1.3/api/health-and-info.md
  content/sensu-core/1.4/api/health-and-info.md
Labels: ready-for-review

#479 Set cursor to pointer for menu dropdowns
  static/stylesheets/override.css
Labels: ready-for-review

#349 Uchiwa/port over existing uchiwa docs
  content/uchiwa/1.0/_index.md
  content/uchiwa/1.0/api/authentication.md
  content/uchiwa/1.0/api/health.md
  content/uchiwa/1.0/contributing.md
  content/uchiwa/1.0/getting-started/basic-concepts.md
  content/uchiwa/1.0/getting-started/configuration.md
  content/uchiwa/1.0/getting-started/installation.md
  content/uchiwa/1.0/guides/high-availability.md
  content/uchiwa/1.0/guides/search-queries.md
  content/uchiwa/1.0/guides/security.md
  content/uchiwa/1.0/guides/troubleshooting.md
  content/uchiwa/1.0/reference/aggregates.md
  content/uchiwa/1.0/reference/checks.md
  content/uchiwa/1.0/reference/clients.md
  content/uchiwa/1.0/reference/events.md
  content/uchiwa/1.0/reference/silencing.md
  content/uchiwa/_index.md
  layouts/index.html
Labels: ready-for-review

#511 Fix bad client name in 1.4 sensu-core
  content/sensu-core/0.29/quick-start/learn-sensu-basics.md
  content/sensu-core/1.0/quick-start/learn-sensu-basics.md
  content/sensu-core/1.1/quick-start/learn-sensu-basics.md
  content/sensu-core/1.2/quick-start/learn-sensu-basics.md
  content/sensu-core/1.3/quick-start/learn-sensu-basics.md
  content/sensu-core/1.4/quick-start/learn-sensu-basics.md
Labels: errata, ready-for-review

#510 Fix typos in Securing RabbitMQ guide
  content/sensu-core/0.29/guides/securing-rabbitmq.md
  content/sensu-core/1.0/guides/securing-rabbitmq.md
  content/sensu-core/1.1/guides/securing-rabbitmq.md
  content/sensu-core/1.2/guides/securing-rabbitmq.md
  content/sensu-core/1.3/guides/securing-rabbitmq.md
  content/sensu-core/1.4/guides/securing-rabbitmq.md
Labels: ready-for-review

#495 Add note about requiring a custom attribute for email template.
  content/sensu-enterprise/2.6/integrations/email.md
  content/sensu-enterprise/2.7/integrations/email.md
  content/sensu-enterprise/2.8/integrations/email.md
  content/sensu-enterprise/3.0/integrations/email.md
Labels: ready-for-review

#512 Add mention of sensu/sensu-go#1700 in assets reference docs
  content/sensu-core/2.0/reference/assets.md
Labels: ready-for-review

#513 add redirect rule for /uchiwa/latest
  static.json
Labels: ready-for-review

#515 Unfurl page-specific metadata
  config.toml
  layouts/partials/head.html
  static/images/sensu-logo-icon-dark@128px.png
Labels: ready-for-review

#516 fixed missing step and typo
  content/sensu-core/1.4/quick-start/five-minute-install.md
Labels: ready-for-review

#519 Add section landing pages for Sensu Core 2.0
  content/sensu-core/2.0/getting-started/_index.md
  content/sensu-core/2.0/guides/_index.md
  content/sensu-core/2.0/reference/_index.md
Labels: ready-for-review

#520 Fix links
  content/plugins/1.0/_index.md
  content/sensu-core/0.29/installation/install-a-dashboard.md
  content/sensu-core/0.29/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.0/installation/install-a-dashboard.md
  content/sensu-core/1.0/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.1/installation/install-a-dashboard.md
  content/sensu-core/1.1/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.2/installation/install-a-dashboard.md
  content/sensu-core/1.2/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.3/installation/install-a-dashboard.md
  content/sensu-core/1.3/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.4/installation/install-a-dashboard.md
  content/sensu-core/1.4/platforms/sensu-on-mac-os-x.md
Labels: ready-for-review

#338 Securing Redis Guide
  content/sensu-core/0.29/guides/securing-redis.md
  content/sensu-core/1.0/guides/securing-redis.md
  content/sensu-core/1.1/guides/securing-redis.md
  content/sensu-core/1.2/guides/securing-redis.md
  content/sensu-core/1.3/guides/securing-redis.md
  content/sensu-core/1.4/guides/securing-redis.md
Labels: ready-for-review

#523 Update ansible gem docs
  content/plugins/1.0/installation.md
Labels: ready-for-review

#526 add changelog for Sensu Enterprise 3.0.1
  content/sensu-enterprise/3.0/changelog.md
Labels: ready-for-review

#531 Add product frontmatter to Securing Redis guide
  content/sensu-core/0.29/guides/securing-redis.md
  content/sensu-core/1.0/guides/securing-redis.md
  content/sensu-core/1.1/guides/securing-redis.md
  content/sensu-core/1.2/guides/securing-redis.md
  content/sensu-core/1.3/guides/securing-redis.md
  content/sensu-core/1.4/guides/securing-redis.md
Labels: ready-for-review

#533 Removing spaces
  content/sensu-enterprise/2.6/installation/testing-prereleases.md
  content/sensu-enterprise/2.7/installation/testing-prereleases.md
  content/sensu-enterprise/2.8/installation/testing-prereleases.md
  content/sensu-enterprise/3.0/installation/testing-prereleases.md
Labels: ready-for-review

#534 Removing relics
  content/plugins/1.0/gsoc.md
  content/plugins/1.0/tom-servo.md
Labels: ready-for-review
