Repository sensu/sensu-docs, pull requests merged in 2019-01, with the labels that each got.

#1055 Add changelog details for 2.13
  content/sensu-enterprise-dashboard/2.13/changelog.md
Labels: in progress

#1056 Add Enterprise Dashboard 2.14
  config.toml
  content/sensu-enterprise-dashboard/2.14/_index.md
  content/sensu-enterprise-dashboard/2.14/api/_index.md
  content/sensu-enterprise-dashboard/2.14/api/aggregates.md
  content/sensu-enterprise-dashboard/2.14/api/checks.md
  content/sensu-enterprise-dashboard/2.14/api/clients.md
  content/sensu-enterprise-dashboard/2.14/api/config.md
  content/sensu-enterprise-dashboard/2.14/api/datacenters.md
  content/sensu-enterprise-dashboard/2.14/api/events.md
  content/sensu-enterprise-dashboard/2.14/api/health.md
  content/sensu-enterprise-dashboard/2.14/api/overview.md
  content/sensu-enterprise-dashboard/2.14/api/results.md
  content/sensu-enterprise-dashboard/2.14/api/silenced.md
  content/sensu-enterprise-dashboard/2.14/api/stashes.md
  content/sensu-enterprise-dashboard/2.14/api/subscriptions.md
  content/sensu-enterprise-dashboard/2.14/changelog.md
  content/sensu-enterprise-dashboard/2.14/collections.md
  content/sensu-enterprise-dashboard/2.14/configuration.md
  content/sensu-enterprise-dashboard/2.14/hud.md
  content/sensu-enterprise-dashboard/2.14/rbac/_index.md
  content/sensu-enterprise-dashboard/2.14/rbac/audit-logging.md
  content/sensu-enterprise-dashboard/2.14/rbac/overview.md
  content/sensu-enterprise-dashboard/2.14/rbac/rbac-for-github.md
  content/sensu-enterprise-dashboard/2.14/rbac/rbac-for-gitlab.md
  content/sensu-enterprise-dashboard/2.14/rbac/rbac-for-ldap.md
  content/sensu-enterprise-dashboard/2.14/rbac/rbac-for-oidc.md
  static.json
Labels: in progress

#1066 Correct attribute specifications and names
  content/sensu-go/5.0/api/cluster-roles.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/entities.md
  content/sensu-go/5.0/reference/mutators.md
  content/sensu-go/5.0/reference/rbac.md
  content/sensu-go/5.1/api/cluster-roles.md
  content/sensu-go/5.1/reference/checks.md
  content/sensu-go/5.1/reference/entities.md
  content/sensu-go/5.1/reference/mutators.md
  content/sensu-go/5.1/reference/rbac.md
Labels: ready-for-review

#1070 Update RBAC API docs
  content/sensu-go/5.0/api/cluster-role-bindings.md
  content/sensu-go/5.0/api/cluster-roles.md
  content/sensu-go/5.0/api/namespaces.md
  content/sensu-go/5.0/api/role-bindings.md
  content/sensu-go/5.0/api/roles.md
  content/sensu-go/5.1/api/cluster-role-bindings.md
  content/sensu-go/5.1/api/cluster-roles.md
  content/sensu-go/5.1/api/namespaces.md
  content/sensu-go/5.1/api/role-bindings.md
  content/sensu-go/5.1/api/roles.md
Labels: ready-for-review

#1072 Update site footer to match sensu.io
  layouts/partials/footer.html
Labels: ready-for-review

#1073 Replicates guide across versions
  content/sensu-enterprise/2.6/guides/email-gsuite.md
  content/sensu-enterprise/2.7/guides/email-gsuite.md
  content/sensu-enterprise/2.8/guides/email-gsuite.md
  content/sensu-enterprise/3.0/guides/email-gsuite.md
  content/sensu-enterprise/3.1/guides/email-gsuite.md
  content/sensu-enterprise/3.2/guides/email-gsuite.md
Labels: in progress

#1059 Securing Sensu Go requires modification of api-url parameter
  content/sensu-go/5.0/guides/securing-sensu.md
  content/sensu-go/5.1/guides/securing-sensu.md
Labels: ready-for-review

#1060 Fixing some broken urls
  content/sensu-go/5.0/dashboard/overview.md
  content/sensu-go/5.0/getting-started/glossary.md
  content/sensu-go/5.0/guides/monitor-server-resources.md
  content/sensu-go/5.0/guides/plan-maintenance.md
  content/sensu-go/5.1/dashboard/overview.md
  content/sensu-go/5.1/getting-started/glossary.md
  content/sensu-go/5.1/guides/monitor-server-resources.md
  content/sensu-go/5.1/guides/plan-maintenance.md
Labels: ready-for-review

#1076 Errata fixes: new and improved sections, sensuctl quick reference
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.0/reference/hooks.md
  content/sensu-go/5.0/reference/sensu-query-expressions.md
  content/sensu-go/5.0/reference/silencing.md
  content/sensu-go/5.0/sensuctl/quickstart.md
  content/sensu-go/5.0/sensuctl/reference.md
  content/sensu-go/5.1/reference/agent.md
  content/sensu-go/5.1/reference/backend.md
  content/sensu-go/5.1/reference/checks.md
  content/sensu-go/5.1/reference/handlers.md
  content/sensu-go/5.1/reference/hooks.md
  content/sensu-go/5.1/reference/sensu-query-expressions.md
  content/sensu-go/5.1/reference/silencing.md
  content/sensu-go/5.1/sensuctl/quickstart.md
  content/sensu-go/5.1/sensuctl/reference.md
Labels: in progress

#1081 Update Sensu query expression reference link
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.1/reference/checks.md
Labels: ready-for-review

#1086 Fix example metric output_format configuration
  content/sensu-enterprise/2.6/built-in-mutators.md
  content/sensu-enterprise/2.7/built-in-mutators.md
  content/sensu-enterprise/2.8/built-in-mutators.md
  content/sensu-enterprise/3.0/built-in-mutators.md
  content/sensu-enterprise/3.1/built-in-mutators.md
  content/sensu-enterprise/3.2/built-in-mutators.md
  content/sensu-enterprise/3.3/built-in-mutators.md
Labels: in progress

#1087 Update upgrading guide
  content/sensu-enterprise-dashboard/2.14/changelog.md
  content/sensu-go/5.0/getting-started/glossary.md
  content/sensu-go/5.0/installation/upgrade.md
  content/sensu-go/5.1/api/overview.md
  content/sensu-go/5.1/getting-started/glossary.md
  content/sensu-go/5.1/installation/upgrade.md
Labels: in progress

#1089 Correct link to learn puppet
  content/sensu-core/0.29/installation/configuration-management.md
  content/sensu-core/1.0/installation/configuration-management.md
  content/sensu-core/1.1/installation/configuration-management.md
  content/sensu-core/1.2/installation/configuration-management.md
  content/sensu-core/1.3/installation/configuration-management.md
  content/sensu-core/1.4/installation/configuration-management.md
  content/sensu-core/1.5/installation/configuration-management.md
  content/sensu-core/1.6/installation/configuration-management.md
  content/sensu-go/5.0/installation/configuration-management.md
  content/sensu-go/5.1/installation/configuration-management.md
Labels: in progress

#1090 Document http_proxy parameter for integrations which support it
  content/sensu-enterprise/2.6/integrations/jira.md
  content/sensu-enterprise/2.6/integrations/puppet.md
  content/sensu-enterprise/2.6/integrations/rollbar.md
  content/sensu-enterprise/2.6/integrations/servicenow.md
  content/sensu-enterprise/2.7/integrations/jira.md
  content/sensu-enterprise/2.7/integrations/puppet.md
  content/sensu-enterprise/2.7/integrations/rollbar.md
  content/sensu-enterprise/2.7/integrations/servicenow.md
  content/sensu-enterprise/2.8/integrations/jira.md
  content/sensu-enterprise/2.8/integrations/puppet.md
  content/sensu-enterprise/2.8/integrations/rollbar.md
  content/sensu-enterprise/2.8/integrations/servicenow.md
  content/sensu-enterprise/3.0/integrations/jira.md
  content/sensu-enterprise/3.0/integrations/opsgenie.md
  content/sensu-enterprise/3.0/integrations/puppet.md
  content/sensu-enterprise/3.0/integrations/rollbar.md
  content/sensu-enterprise/3.0/integrations/servicenow.md
  content/sensu-enterprise/3.0/integrations/victorops.md
  content/sensu-enterprise/3.1/integrations/jira.md
  content/sensu-enterprise/3.1/integrations/opsgenie.md
  content/sensu-enterprise/3.1/integrations/puppet.md
  content/sensu-enterprise/3.1/integrations/rollbar.md
  content/sensu-enterprise/3.1/integrations/servicenow.md
  content/sensu-enterprise/3.1/integrations/victorops.md
  content/sensu-enterprise/3.2/integrations/jira.md
  content/sensu-enterprise/3.2/integrations/opsgenie.md
  content/sensu-enterprise/3.2/integrations/puppet.md
  content/sensu-enterprise/3.2/integrations/rollbar.md
  content/sensu-enterprise/3.2/integrations/servicenow.md
  content/sensu-enterprise/3.2/integrations/victorops.md
  content/sensu-enterprise/3.3/integrations/jira.md
  content/sensu-enterprise/3.3/integrations/opsgenie.md
  content/sensu-enterprise/3.3/integrations/puppet.md
  content/sensu-enterprise/3.3/integrations/rollbar.md
  content/sensu-enterprise/3.3/integrations/servicenow.md
  content/sensu-enterprise/3.3/integrations/victorops.md
Labels: in progress

#1091 [WIP] Add Sensu Enterprise version 3.3.2
  content/sensu-enterprise/3.3/changelog.md
Labels: in progress

#1093 Update `http_proxy` attributes in InfluxDB, Librato, and VictorOps integrations
  content/sensu-enterprise/2.6/integrations/influxdb.md
  content/sensu-enterprise/2.6/integrations/librato.md
  content/sensu-enterprise/2.7/integrations/influxdb.md
  content/sensu-enterprise/2.7/integrations/librato.md
  content/sensu-enterprise/2.8/integrations/influxdb.md
  content/sensu-enterprise/2.8/integrations/librato.md
  content/sensu-enterprise/3.0/integrations/influxdb.md
  content/sensu-enterprise/3.0/integrations/librato.md
  content/sensu-enterprise/3.0/integrations/victorops.md
  content/sensu-enterprise/3.1/integrations/influxdb.md
  content/sensu-enterprise/3.1/integrations/librato.md
  content/sensu-enterprise/3.1/integrations/victorops.md
  content/sensu-enterprise/3.2/integrations/influxdb.md
  content/sensu-enterprise/3.2/integrations/librato.md
  content/sensu-enterprise/3.2/integrations/victorops.md
  content/sensu-enterprise/3.3/integrations/influxdb.md
  content/sensu-enterprise/3.3/integrations/librato.md
  content/sensu-enterprise/3.3/integrations/victorops.md
Labels: in progress

#1083 Update release notes format
  content/sensu-go/5.0/installation/upgrade.md
  content/sensu-go/5.0/release-notes.md
  content/sensu-go/5.1/installation/upgrade.md
  content/sensu-go/5.1/release-notes.md
Labels: in progress

#866 Guide/contact routing
  content/sensu-enterprise/2.6/guides/using-contact-routing.md
  content/sensu-enterprise/2.7/guides/using-contact-routing.md
  content/sensu-enterprise/2.8/guides/using-contact-routing.md
  content/sensu-enterprise/3.0/guides/using-contact-routing.md
  content/sensu-enterprise/3.1/guides/using-contact-routing.md
  content/sensu-enterprise/3.2/guides/using-contact-routing.md
  content/sensu-enterprise/3.3/guides/using-contact-routing.md
  static/images/contact-routing/contact-routing-MEP.png
  static/images/contact-routing/multiple-handlers/matching-contact.png
  static/images/contact-routing/multiple-handlers/multiple-matching-contacts.png
  static/images/contact-routing/multiple-handlers/multiple-non-matching-contacts.png
  static/images/contact-routing/multiple-handlers/single-matching-contact.png
  static/images/contact-routing/multiple-handlers/single-non-matching-contact.png
  static/images/contact-routing/multiple-handlers/some-matching-contacts.png
  static/images/contact-routing/single-handler/multiple-matching-contacts.png
  static/images/contact-routing/single-handler/multiple-non-matching-contacts.png
  static/images/contact-routing/single-handler/single-matching-contact.png
  static/images/contact-routing/single-handler/single-non-matching-contact.png
  static/images/contact-routing/single-handler/some-matching-contacts.png
Labels: in progress

#1096 Removes errant duplicate securing doc
  content/sensu-go/5.1/guides/securing-sensu.1.md
  content/sensu-go/5.1/guides/securing-sensu.md
Labels: in progress

#1104 Updates to doc using minikube
  content/sensu-go/5.0/getting-started/sample-app.md
Labels: in progress

#1111 Update influx-db-metric-handler.md
  content/sensu-go/5.0/api/handlers.md
  content/sensu-go/5.0/guides/influx-db-metric-handler.md
  content/sensu-go/5.0/guides/install-check-executables-with-assets.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.1/api/handlers.md
  content/sensu-go/5.1/guides/influx-db-metric-handler.md
  content/sensu-go/5.1/guides/install-check-executables-with-assets.md
  content/sensu-go/5.1/reference/filters.md
Labels: ready-for-review

#1098 Style text within tables
  static/stylesheets/docs-overrides.css
Labels: in progress

#1110 Add definitions for round_robin and subdue check attributes
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.1/reference/checks.md
Labels: in progress

#1106 Update error text when Sensu Enterprise 3.1 and prior is given an encrypted private key
  content/sensu-enterprise/2.6/guides/troubleshooting.md
  content/sensu-enterprise/2.7/guides/troubleshooting.md
  content/sensu-enterprise/2.8/guides/troubleshooting.md
  content/sensu-enterprise/3.0/guides/troubleshooting.md
  content/sensu-enterprise/3.1/guides/troubleshooting.md
Labels: ready-for-review

#1107 Correct agent API docs
  content/sensu-go/5.0/api/overview.md
  content/sensu-go/5.0/reference/agent.md
  content/sensu-go/5.1/api/overview.md
  content/sensu-go/5.1/reference/agent.md
Labels: ready-for-review

#1092 Update cluster guide to include agent configuration
  content/sensu-go/5.1/guides/clustering.md
Labels: ready-for-review

#1108 Add that agents are namespaced
  content/sensu-go/5.0/reference/agent.md
  content/sensu-go/5.0/reference/rbac.md
Labels: ready-for-review

#1113 Sensu Go cluster agent update copy to all versions
  content/sensu-go/5.0/guides/clustering.md
Labels: in progress

#1116 Update proxy request PR
  content/sensu-go/5.0/guides/monitor-external-resources.md
  content/sensu-go/5.0/reference/checks.md
Labels: in progress

#1112 Agents are namespaced copy to all versions
  content/sensu-go/5.0/reference/rbac.md
  content/sensu-go/5.1/reference/agent.md
  content/sensu-go/5.1/reference/rbac.md
Labels: in progress

#1115 Add plugin install reference to monitor the monitor
  content/sensu-core/0.29/guides/monitor-the-monitor.md
  content/sensu-core/1.0/guides/monitor-the-monitor.md
  content/sensu-core/1.1/guides/monitor-the-monitor.md
  content/sensu-core/1.2/guides/monitor-the-monitor.md
  content/sensu-core/1.3/guides/monitor-the-monitor.md
  content/sensu-core/1.4/guides/monitor-the-monitor.md
  content/sensu-core/1.5/guides/monitor-the-monitor.md
  content/sensu-core/1.6/guides/monitor-the-monitor.md
Labels: in progress

#1085 Add more Sensu Go FAQs
  content/sensu-go/5.0/getting-started/faq.md
  content/sensu-go/5.1/getting-started/faq.md
Labels: ready-for-review

#1082 Add known token limitations to check reference
  content/sensu-core/0.29/reference/checks.md
  content/sensu-core/1.0/reference/checks.md
  content/sensu-core/1.1/reference/checks.md
  content/sensu-core/1.2/reference/checks.md
  content/sensu-core/1.3/reference/checks.md
  content/sensu-core/1.4/reference/checks.md
  content/sensu-core/1.5/reference/checks.md
  content/sensu-core/1.6/reference/checks.md
Labels: ready-for-review

#1103 Noting all sections must be completed for secure comms.
  content/sensu-go/5.0/guides/securing-sensu.md
  content/sensu-go/5.1/guides/securing-sensu.md
Labels: in progress

#1025 Sample app tutorial
  content/sensu-go/5.0/getting-started/get-started.md
  content/sensu-go/5.0/getting-started/sample-app.md
  content/sensu-go/5.1/getting-started/get-started.md
  content/sensu-go/5.1/getting-started/sample-app.md
Labels: 5.x, in progress

#1117 Sensu 1.x API and Sensu Enterprise Dashboard config updates
  content/sensu-core/0.29/api/overview.md
  content/sensu-core/1.0/api/overview.md
  content/sensu-core/1.1/api/overview.md
  content/sensu-core/1.2/api/overview.md
  content/sensu-core/1.3/api/overview.md
  content/sensu-core/1.4/api/overview.md
  content/sensu-core/1.5/api/overview.md
  content/sensu-core/1.6/api/overview.md
  content/sensu-enterprise-dashboard/2.10/configuration.md
  content/sensu-enterprise-dashboard/2.11/configuration.md
  content/sensu-enterprise-dashboard/2.12/configuration.md
  content/sensu-enterprise-dashboard/2.13/configuration.md
  content/sensu-enterprise-dashboard/2.14/configuration.md
  content/sensu-enterprise-dashboard/2.9/configuration.md
Labels: in progress

#1121 Reorder guides
  content/sensu-go/5.0/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.0/guides/enrich-events-with-hooks.md
  content/sensu-go/5.0/guides/extract-metrics-with-checks.md
  content/sensu-go/5.0/guides/influx-db-metric-handler.md
  content/sensu-go/5.0/guides/install-check-executables-with-assets.md
  content/sensu-go/5.0/guides/reduce-alert-fatigue.md
  content/sensu-go/5.0/guides/send-slack-alerts.md
  content/sensu-go/5.1/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.1/guides/enrich-events-with-hooks.md
  content/sensu-go/5.1/guides/extract-metrics-with-checks.md
  content/sensu-go/5.1/guides/influx-db-metric-handler.md
  content/sensu-go/5.1/guides/install-check-executables-with-assets.md
  content/sensu-go/5.1/guides/reduce-alert-fatigue.md
  content/sensu-go/5.1/guides/send-slack-alerts.md
Labels: ready-for-review

#1123 Update client-to-server transport documentation
  content/sensu-go/5.0/guides/clustering.md
  content/sensu-go/5.1/guides/clustering.md
Labels: ready-for-review

#1124 Add missing subscriptions payload parameter
  content/sensu-go/5.0/api/checks.md
  content/sensu-go/5.1/api/checks.md
Labels: in progress

#1128 Adjust font sizes in sidebar menu
  static/stylesheets/docs-overrides.css
  static/stylesheets/override.css
Labels: ready-for-review

#1125 Add sandbox lesson
  content/sensu-go/5.0/getting-started/get-started.md
  content/sensu-go/5.0/getting-started/sandbox.md
  content/sensu-go/5.1/getting-started/get-started.md
  content/sensu-go/5.1/getting-started/sandbox.md
Labels: ready-for-review

#1109 Document enterprise metrics API
  content/sensu-enterprise/3.3/api.md
Labels: ready-for-review

#1135 Change redirects in static.json from 302 to 301
  static.json
Labels: ready-for-review

#885 Add a proxy_requests section and various fixes/updating wording
  content/sensu-go/5.0/guides/monitor-external-resources.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.1/guides/monitor-external-resources.md
  content/sensu-go/5.1/reference/checks.md
Labels: ready-for-review

#1138 Correct client install next page link
  content/sensu-core/0.29/installation/install-sensu-client.md
Labels: ready-for-review

#1147 Reorganize getting started content
  content/sensu-go/5.0/_index.md
  content/sensu-go/5.0/getting-started/get-started.md
  content/sensu-go/5.0/getting-started/learn-sensu.md
  content/sensu-go/5.0/getting-started/sample-app.md
  content/sensu-go/5.0/getting-started/sandbox.md
  content/sensu-go/5.1/_index.md
  content/sensu-go/5.1/getting-started/get-started.md
  content/sensu-go/5.1/getting-started/learn-sensu.md
  content/sensu-go/5.1/getting-started/sample-app.md
  content/sensu-go/5.1/getting-started/sandbox.md
  content/sensu-go/5.1/reference/assets.md
  content/sensu-go/5.1/reference/checks.md
  content/sensu-go/5.1/reference/entities.md
  content/sensu-go/5.1/reference/filters.md
  content/sensu-go/5.1/reference/handlers.md
  content/sensu-go/5.1/reference/hooks.md
  content/sensu-go/5.1/reference/mutators.md
  content/sensu-go/5.1/reference/silencing.md
  content/sensu-go/5.2/_index.md
  content/sensu-go/5.2/getting-started/get-started.md
  content/sensu-go/5.2/getting-started/learn-sensu.md
  content/sensu-go/5.2/getting-started/sample-app.md
  content/sensu-go/5.2/getting-started/sandbox.md
  content/sensu-go/5.2/reference/assets.md
  content/sensu-go/5.2/reference/checks.md
  content/sensu-go/5.2/reference/entities.md
  content/sensu-go/5.2/reference/filters.md
  content/sensu-go/5.2/reference/handlers.md
  content/sensu-go/5.2/reference/hooks.md
  content/sensu-go/5.2/reference/mutators.md
  content/sensu-go/5.2/reference/silencing.md
  static/images/pipeline-ce.svg
  static/images/system-ce.png
Labels: ready-for-review

#1146 [WIP] Jira issue_type note
  content/sensu-enterprise/2.6/integrations/jira.md
  content/sensu-enterprise/2.7/integrations/jira.md
  content/sensu-enterprise/2.8/integrations/jira.md
  content/sensu-enterprise/3.0/integrations/jira.md
  content/sensu-enterprise/3.1/integrations/jira.md
  content/sensu-enterprise/3.2/integrations/jira.md
  content/sensu-enterprise/3.3/integrations/jira.md
Labels: in progress
