Repository sensu/sensu-docs, pull requests merged in 2019-02, with the labels that each got.

#1156 link to the Sensu License from Sensu Go installation doc
  content/sensu-go/5.0/installation/install-sensu.md
  content/sensu-go/5.1/installation/install-sensu.md
  content/sensu-go/5.2/installation/install-sensu.md
Labels: in progress

#1149 Add new check attributes
  content/sensu-go/5.2/reference/checks.md
Labels: in progress

#1137 Update possible client transport configuration requirement
  content/sensu-core/0.29/platforms/sensu-on-freebsd.md
  content/sensu-core/0.29/platforms/sensu-on-ibm-aix.md
  content/sensu-core/0.29/platforms/sensu-on-mac-os-x.md
  content/sensu-core/0.29/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/0.29/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/0.29/platforms/sensu-on-rhel-centos.md
  content/sensu-core/0.29/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.0/platforms/sensu-on-freebsd.md
  content/sensu-core/1.0/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.0/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.0/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.0/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/1.0/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.0/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.1/platforms/sensu-on-freebsd.md
  content/sensu-core/1.1/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.1/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.1/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.1/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/1.1/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.1/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.2/platforms/sensu-on-freebsd.md
  content/sensu-core/1.2/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.2/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.2/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.2/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/1.2/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.2/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.3/platforms/sensu-on-freebsd.md
  content/sensu-core/1.3/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.3/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.3/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.3/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/1.3/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.3/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.4/platforms/sensu-on-freebsd.md
  content/sensu-core/1.4/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.4/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.4/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.4/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/1.4/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.4/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.5/platforms/sensu-on-freebsd.md
  content/sensu-core/1.5/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.5/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.5/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.5/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/1.5/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.5/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.6/platforms/sensu-on-freebsd.md
  content/sensu-core/1.6/platforms/sensu-on-ibm-aix.md
  content/sensu-core/1.6/platforms/sensu-on-mac-os-x.md
  content/sensu-core/1.6/platforms/sensu-on-microsoft-windows.md
  content/sensu-core/1.6/platforms/sensu-on-oracle-solaris.md
  content/sensu-core/1.6/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.6/platforms/sensu-on-ubuntu-debian.md
Labels: in progress

#1163 Modify grammar for clarity
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.1/reference/checks.md
  content/sensu-go/5.2/reference/checks.md
Labels: ready-for-review

#1164 Fix link
  content/sensu-go/5.0/installation/upgrade.md
  content/sensu-go/5.1/installation/upgrade.md
  content/sensu-go/5.2/installation/upgrade.md
Labels: in progress

#1150 Document LDAP authentication
  content/sensu-go/5.2/api/auth.md
  content/sensu-go/5.2/api/authproviders.md
  content/sensu-go/5.2/installation/auth.md
  content/sensu-go/5.2/reference/rbac.md
  content/sensu-go/5.2/sensuctl/reference.md
Labels: ready-for-review

#1152 License reference and API docs
  content/sensu-go/5.2/api/license.md
  content/sensu-go/5.2/reference/license.md
Labels: ready-for-review

#1162 Document Debian support and binary download options for Sensu Go 5.2
  content/sensu-go/5.2/getting-started/platforms.md
  content/sensu-go/5.2/installation/install-sensu.md
  content/sensu-go/5.2/installation/verify.md
  content/sensu-go/5.2/reference/agent.md
  content/sensu-go/5.2/reference/backend.md
Labels: ready-for-review

#1171 Add RBAC example and fixups
  content/sensu-go/5.2/installation/auth.md
  content/sensu-go/5.2/installation/install-sensu.md
Labels: ready-for-review

#1153 Sensu Go 5.2 release notes
  content/sensu-go/5.2/release-notes.md
Labels: ready-for-review

#1154 Bonsai & assets
  content/sensu-go/5.2/_index.md
  content/sensu-go/5.2/guides/install-check-executables-with-assets.md
  content/sensu-go/5.2/reference/assets.md
  content/sensu-go/5.2/reference/checks.md
  content/sensu-go/5.2/reference/handlers.md
Labels: ready-for-review

#1170 Promote 5.2 to latest version of Sensu Go docs
  config.toml
  static.json
Labels: in progress

#1169 remove repeated metadata scope
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.1/reference/handlers.md
  content/sensu-go/5.2/reference/handlers.md
Labels: in progress

#1172 Address review feedback on asset PR
  content/sensu-go/5.1/release-notes.md
  content/sensu-go/5.2/_index.md
  content/sensu-go/5.2/guides/install-check-executables-with-assets.md
  content/sensu-go/5.2/reference/assets.md
  content/sensu-go/5.2/release-notes.md
Labels: in progress

#1176 Add note to release notes about binary names
  content/sensu-go/5.2/release-notes.md
Labels: in progress

#1177 Quick fix: Better wording
  content/sensu-go/5.2/release-notes.md
Labels: in progress

#1175 Incorporate getting started feedback
  content/sensu-go/5.2/getting-started/get-started.md
Labels: in progress

#1173 Add troubleshooting guide for LDAP
  content/sensu-go/5.2/installation/auth.md
Labels: in progress

#1179 updating meta description
  content/sensu-go/5.2/release-notes.md
Labels: in progress

#1184 Update version numbers in API overview
  content/sensu-go/5.1/api/overview.md
  content/sensu-go/5.2/api/overview.md
Labels: ready-for-review

#1134 Update silenced.md
  content/sensu-core/0.29/api/silenced.md
  content/sensu-core/1.0/api/silenced.md
  content/sensu-core/1.1/api/silenced.md
  content/sensu-core/1.2/api/silenced.md
  content/sensu-core/1.3/api/silenced.md
  content/sensu-core/1.4/api/silenced.md
  content/sensu-core/1.5/api/silenced.md
  content/sensu-core/1.6/api/silenced.md
Labels: ready-for-review

#1183 Update docs for Sensu Go v5.2.1
  content/sensu-go/5.2/installation/install-sensu.md
  content/sensu-go/5.2/installation/verify.md
  content/sensu-go/5.2/reference/agent.md
  content/sensu-go/5.2/reference/backend.md
  content/sensu-go/5.2/release-notes.md
Labels: in progress

#1188 Fix SEO description
  content/sensu-go/5.2/release-notes.md
Labels: in progress

#1182 Add enhancement option to issue template
  .github/ISSUE_TEMPLATE.md
Labels: ready-for-review

#1058 Guide to use Prometheus collector with Sensu Go
  content/sensu-go/5.0/files/up_or_down_dashboard.json
  content/sensu-go/5.0/getting-started/prometheus-metrics.md
  static/images/prometheus-collector/up_or_down_detail.png
Labels: ready-for-review

#1192 Correct sensuctl OSX install instructions
  content/sensu-go/5.0/installation/install-sensu.md
  content/sensu-go/5.2/installation/install-sensu.md
Labels: ready-for-review

#1168 Add minimum required configuration examples
  content/sensu-go/5.0/reference/assets.md
  content/sensu-go/5.0/reference/checks.md
  content/sensu-go/5.0/reference/filters.md
  content/sensu-go/5.0/reference/handlers.md
  content/sensu-go/5.0/reference/mutators.md
  content/sensu-go/5.1/reference/assets.md
  content/sensu-go/5.1/reference/checks.md
  content/sensu-go/5.1/reference/filters.md
  content/sensu-go/5.1/reference/handlers.md
  content/sensu-go/5.1/reference/mutators.md
  content/sensu-go/5.2/reference/assets.md
  content/sensu-go/5.2/reference/checks.md
  content/sensu-go/5.2/reference/filters.md
  content/sensu-go/5.2/reference/handlers.md
  content/sensu-go/5.2/reference/mutators.md
Labels: ready-for-review

#1198 Update role and role binding API docs
  content/sensu-go/5.0/api/cluster-roles.md
  content/sensu-go/5.0/api/health.md
  content/sensu-go/5.0/api/role-bindings.md
  content/sensu-go/5.0/api/roles.md
  content/sensu-go/5.1/api/cluster-roles.md
  content/sensu-go/5.1/api/health.md
  content/sensu-go/5.1/api/role-bindings.md
  content/sensu-go/5.1/api/roles.md
  content/sensu-go/5.2/api/cluster-role-bindings.md
  content/sensu-go/5.2/api/cluster-roles.md
  content/sensu-go/5.2/api/health.md
  content/sensu-go/5.2/api/role-bindings.md
  content/sensu-go/5.2/api/roles.md
Labels: ready-for-review

#1199 Fix health API path
  content/sensu-go/5.0/api/health.md
  content/sensu-go/5.1/api/health.md
  content/sensu-go/5.2/api/health.md
Labels: in progress

#1193 Add trusted ca to securing guide
  content/sensu-go/5.0/guides/securing-sensu.md
  content/sensu-go/5.1/guides/securing-sensu.md
  content/sensu-go/5.2/guides/securing-sensu.md
Labels: in progress

#1207 Fix enterprise command in install guide
  content/sensu-go/5.2/installation/install-sensu.md
Labels: in progress

#1204 Update FAQ w/ question re: Uchiwa & Sensu Go
  content/sensu-go/5.0/getting-started/faq.md
  content/sensu-go/5.1/getting-started/faq.md
  content/sensu-go/5.2/getting-started/faq.md
Labels: 5.x, in progress, update

#1206 Deduplicates ec2 integration content.
  content/sensu-enterprise/3.1/integrations/ec2.md
  content/sensu-enterprise/3.2/integrations/ec2.md
  content/sensu-enterprise/3.3/integrations/ec2.md
Labels: 1.x, in progress, update

#1191 Update windows command syntax
  content/sensu-go/5.0/installation/install-sensu.md
  content/sensu-go/5.0/installation/verify.md
  content/sensu-go/5.1/installation/install-sensu.md
  content/sensu-go/5.1/installation/verify.md
  content/sensu-go/5.2/installation/install-sensu.md
  content/sensu-go/5.2/installation/verify.md
Labels: ready-for-review

#1194 Document dashboard filtering
  content/sensu-go/5.0/dashboard/filtering.md
  content/sensu-go/5.1/dashboard/filtering.md
  content/sensu-go/5.2/dashboard/filtering.md
Labels: ready-for-review

#1208 Fix TOC link to license instructions
  content/sensu-go/5.2/reference/license.md
Labels: in progress

#1201 [Sensu 1.x] Add begin attribute to silencing reference
  content/sensu-core/1.2/reference/silencing.md
  content/sensu-core/1.3/reference/silencing.md
  content/sensu-core/1.4/reference/silencing.md
  content/sensu-core/1.5/reference/silencing.md
  content/sensu-core/1.6/reference/silencing.md
Labels: in progress

#1114 Sensu core supported platforms include Solaris and AIX
  content/sensu-core/0.29/faq.md
  content/sensu-core/1.0/faq.md
  content/sensu-core/1.1/faq.md
  content/sensu-core/1.2/faq.md
  content/sensu-core/1.3/faq.md
  content/sensu-core/1.4/faq.md
  content/sensu-core/1.5/faq.md
  content/sensu-core/1.6/faq.md
Labels: ready-for-review

#1200 Clarify agent socket event format
  content/sensu-go/5.0/reference/agent.md
  content/sensu-go/5.1/reference/agent.md
  content/sensu-go/5.2/reference/agent.md
Labels: ready-for-review

#1212 Enterprise content and continuity fixups
  content/sensu-go/5.0/api/authproviders.md
  content/sensu-go/5.0/api/license.md
  content/sensu-go/5.0/getting-started/enterprise.md
  content/sensu-go/5.0/getting-started/faq.md
  content/sensu-go/5.0/installation/auth.md
  content/sensu-go/5.0/reference/license.md
  content/sensu-go/5.0/reference/rbac.md
  content/sensu-go/5.0/sensuctl/reference.md
  content/sensu-go/5.1/api/authproviders.md
  content/sensu-go/5.1/api/license.md
  content/sensu-go/5.1/getting-started/enterprise.md
  content/sensu-go/5.1/getting-started/faq.md
  content/sensu-go/5.1/installation/auth.md
  content/sensu-go/5.1/reference/license.md
  content/sensu-go/5.1/reference/rbac.md
  content/sensu-go/5.1/sensuctl/reference.md
  content/sensu-go/5.2/getting-started/enterprise.md
  content/sensu-go/5.2/guides/install-check-executables-with-assets.md
  content/sensu-go/5.2/installation/auth.md
  content/sensu-go/5.2/installation/install-sensu.md
  content/sensu-go/5.2/reference/license.md
  content/sensu-go/5.2/reference/rbac.md
  content/sensu-go/5.2/release-notes.md
  content/sensu-go/5.2/sensuctl/reference.md
Labels: in progress

#1220 Use default namespace in entity reference examples
  content/sensu-go/5.0/reference/entities.md
  content/sensu-go/5.1/reference/entities.md
  content/sensu-go/5.2/reference/entities.md
Labels: ready-for-review

#1218 Add response for health API
  content/sensu-core/1.7/api/health-and-info.md
Labels: ready-for-review

#1215 Document global error handling in Sensu Core 1.7
  content/sensu-core/1.7/reference/configuration.md
Labels: ready-for-review

#1217 Note redacted attributes in clients API
  content/sensu-core/1.7/api/clients.md
Labels: ready-for-review

#1224 Add 1.7 changelog
  content/sensu-core/1.7/changelog.md
Labels: in progress

#1225 Document built-in deregistration extension
  content/sensu-core/0.29/reference/clients.md
  content/sensu-core/0.29/reference/server.md
  content/sensu-core/1.0/reference/clients.md
  content/sensu-core/1.0/reference/server.md
  content/sensu-core/1.1/reference/clients.md
  content/sensu-core/1.1/reference/server.md
  content/sensu-core/1.2/reference/clients.md
  content/sensu-core/1.2/reference/server.md
  content/sensu-core/1.3/reference/clients.md
  content/sensu-core/1.3/reference/server.md
  content/sensu-core/1.4/reference/clients.md
  content/sensu-core/1.4/reference/server.md
  content/sensu-core/1.5/reference/clients.md
  content/sensu-core/1.5/reference/server.md
  content/sensu-core/1.6/reference/clients.md
  content/sensu-core/1.6/reference/server.md
  content/sensu-core/1.7/reference/clients.md
  content/sensu-core/1.7/reference/configuration.md
  content/sensu-core/1.7/reference/server.md
Labels: in progress

#1227 Fix links
  content/sensu-core/1.7/changelog.md
  content/sensu-core/1.7/reference/clients.md
Labels: in progress

#1221 Add note that /health does not require authentication and update command
  content/sensu-go/5.0/api/health.md
  content/sensu-go/5.0/api/overview.md
  content/sensu-go/5.1/api/health.md
  content/sensu-go/5.1/api/overview.md
  content/sensu-go/5.2/api/health.md
  content/sensu-go/5.2/api/overview.md
Labels: ready-for-review

#1216 Release Sensu Core 1.7
  config.toml
  static.json
Labels: ready-for-review

#1230 Fix date
  content/sensu-core/1.7/changelog.md
Labels: in progress

#1205 Add config file examples to sensuctl reference.
  content/sensu-go/5.0/sensuctl/reference.md
  content/sensu-go/5.1/sensuctl/reference.md
  content/sensu-go/5.2/sensuctl/reference.md
Labels: 5.x, in progress, update

#1234 Fix link
  content/sensu-go/5.2/sensuctl/reference.md
Labels: in progress

#1226 remove husky and precommit script
  package.json
Labels: in progress

#1232 Add UDP socket examples to agent reference
  content/sensu-go/5.0/reference/agent.md
  content/sensu-go/5.1/reference/agent.md
  content/sensu-go/5.2/reference/agent.md
Labels: ready-for-review

#1219 Update proxy entity reference description
  content/sensu-go/5.0/reference/entities.md
  content/sensu-go/5.1/reference/entities.md
  content/sensu-go/5.2/reference/entities.md
Labels: ready-for-review

#1222 Add script installation to second section in monitoring external resources guide
  content/sensu-go/5.0/guides/monitor-external-resources.md
  content/sensu-go/5.1/guides/monitor-external-resources.md
  content/sensu-go/5.2/guides/monitor-external-resources.md
Labels: ready-for-review

#1238 Allow smaller images
  content/sensu-core/0.29/guides/troubleshooting.md
  content/sensu-core/1.0/guides/troubleshooting.md
  content/sensu-core/1.1/guides/troubleshooting.md
  content/sensu-core/1.2/guides/troubleshooting.md
  content/sensu-core/1.3/guides/troubleshooting.md
  content/sensu-core/1.4/guides/troubleshooting.md
  content/sensu-core/1.5/guides/troubleshooting.md
  content/sensu-core/1.6/guides/troubleshooting.md
  content/sensu-core/1.7/guides/troubleshooting.md
  static/stylesheets/docs-overrides.css
Labels: ready-for-review

#1239 Enable HTTPS for Sensu Enterprise repo URLs
  content/sensu-core/0.29/platforms/sensu-on-rhel-centos.md
  content/sensu-core/0.29/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.0/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.0/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.1/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.1/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.2/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.2/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.3/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.3/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.4/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.4/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.5/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.5/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.6/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.6/platforms/sensu-on-ubuntu-debian.md
  content/sensu-core/1.7/platforms/sensu-on-rhel-centos.md
  content/sensu-core/1.7/platforms/sensu-on-ubuntu-debian.md
  content/sensu-enterprise/2.6/quick-start/five-minute-install.md
  content/sensu-enterprise/2.7/quick-start/five-minute-install.md
  content/sensu-enterprise/2.8/quick-start/five-minute-install.md
  content/sensu-enterprise/3.0/quick-start/five-minute-install.md
  content/sensu-enterprise/3.1/quick-start/five-minute-install.md
  content/sensu-enterprise/3.2/quick-start/five-minute-install.md
  content/sensu-enterprise/3.3/quick-start/five-minute-install.md
Labels: ready-for-review

#1229 Copy to clipboard button
  layouts/_default/single.html
  static/images/clippy.svg
  static/js/clip.js
  static/stylesheets/docs-overrides.css
Labels: in progress
