Repository sensu/sensu-docs, pull requests merged in 2019-12, with the labels that each got.

#1970 Correct address in /auth spec example urls
  content/sensu-go/5.1/api/auth.md
  content/sensu-go/5.10/api/auth.md
  content/sensu-go/5.11/api/auth.md
  content/sensu-go/5.12/api/auth.md
  content/sensu-go/5.13/api/auth.md
  content/sensu-go/5.14/api/auth.md
  content/sensu-go/5.15/api/auth.md
  content/sensu-go/5.16/api/auth.md
  content/sensu-go/5.2/api/auth.md
  content/sensu-go/5.3/api/auth.md
  content/sensu-go/5.4/api/auth.md
  content/sensu-go/5.5/api/auth.md
  content/sensu-go/5.6/api/auth.md
  content/sensu-go/5.7/api/auth.md
  content/sensu-go/5.8/api/auth.md
  content/sensu-go/5.9/api/auth.md
Labels: errata, ready for review

#1965 Add commercial feature note to enterprise datastore guide
  content/sensu-go/5.10/guides/scale-event-storage.md
  content/sensu-go/5.11/guides/scale-event-storage.md
  content/sensu-go/5.12/guides/scale-event-storage.md
  content/sensu-go/5.13/guides/scale-event-storage.md
  content/sensu-go/5.14/guides/scale-event-storage.md
  content/sensu-go/5.15/guides/scale-event-storage.md
  content/sensu-go/5.16/guides/scale-event-storage.md
Labels: ready for review, update

#1964 Replace check example w/example that includes hook in token reference
  content/sensu-go/5.0/reference/tokens.md
  content/sensu-go/5.1/reference/tokens.md
  content/sensu-go/5.10/reference/tokens.md
  content/sensu-go/5.11/reference/tokens.md
  content/sensu-go/5.12/reference/tokens.md
  content/sensu-go/5.13/reference/tokens.md
  content/sensu-go/5.14/reference/tokens.md
  content/sensu-go/5.15/reference/tokens.md
  content/sensu-go/5.16/reference/tokens.md
  content/sensu-go/5.2/reference/tokens.md
  content/sensu-go/5.3/reference/tokens.md
  content/sensu-go/5.4/reference/tokens.md
  content/sensu-go/5.5/reference/tokens.md
  content/sensu-go/5.6/reference/tokens.md
  content/sensu-go/5.7/reference/tokens.md
  content/sensu-go/5.8/reference/tokens.md
  content/sensu-go/5.9/reference/tokens.md
Labels: update

#1980 Update guide nav titles, page titles, and nav order
  content/sensu-go/5.16/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.16/guides/clustering.md
  content/sensu-go/5.16/guides/contact-routing.md
  content/sensu-go/5.16/guides/create-read-only-user.md
  content/sensu-go/5.16/guides/deploying.md
  content/sensu-go/5.16/guides/enrich-events-with-hooks.md
  content/sensu-go/5.16/guides/extract-metrics-with-checks.md
  content/sensu-go/5.16/guides/influx-db-metric-handler.md
  content/sensu-go/5.16/guides/install-check-executables-with-assets.md
  content/sensu-go/5.16/guides/monitor-external-resources.md
  content/sensu-go/5.16/guides/monitor-server-resources.md
  content/sensu-go/5.16/guides/plan-maintenance.md
  content/sensu-go/5.16/guides/reduce-alert-fatigue.md
  content/sensu-go/5.16/guides/scale-event-storage.md
  content/sensu-go/5.16/guides/securing-sensu.md
  content/sensu-go/5.16/guides/send-slack-alerts.md
  content/sensu-go/5.16/guides/systemd-logs.md
  content/sensu-go/5.16/guides/troubleshooting.md
  content/sensu-go/5.16/guides/use-apikey-feature.md
Labels: improvement, ready for review

#1987 Add privacy policy link in footer on every page of docs
  layouts/partials/footer.html
Labels: improvement, ready for review

#1981 Copy edit 5.16 index page page and release notes
  content/sensu-go/5.16/_index.md
  content/sensu-go/5.16/release-notes.md
Labels: improvement, ready for review

#1994 Correct some out of date info about the datastore
  content/sensu-go/5.15/reference/datastore.md
  content/sensu-go/5.16/reference/datastore.md
Labels: errata

#1989 Copy edit 5.16 sensuctl articles
  content/sensu-go/5.16/sensuctl/quickstart.md
  content/sensu-go/5.16/sensuctl/reference.md
Labels: improvement, ready for review

#1988 Copy edit 5.16 dashboard articles
  content/sensu-go/5.16/dashboard/filtering.md
  content/sensu-go/5.16/dashboard/overview.md
Labels: improvement, ready for review

#1960 Add etcd discovery flags
  content/sensu-go/5.16/reference/backend.md
Labels: ready for review

#1991 Add keepalive-critical-timeout flag to agent reference
  content/sensu-go/5.16/files/agent.yml
  content/sensu-go/5.16/files/windows/agent.yml
  content/sensu-go/5.16/reference/agent.md
Labels: new feature, ready for review

#2006 Add etcd-client-urls flag in backend reference
  content/sensu-go/5.16/reference/backend.md
Labels: ready for review

#2013 Replace journalctl -u with journalctl _COMM=
  content/sensu-go/5.12/guides/troubleshooting.md
  content/sensu-go/5.12/reference/tessen.md
  content/sensu-go/5.13/guides/troubleshooting.md
  content/sensu-go/5.13/reference/tessen.md
  content/sensu-go/5.14/guides/troubleshooting.md
  content/sensu-go/5.14/reference/tessen.md
  content/sensu-go/5.15/guides/troubleshooting.md
  content/sensu-go/5.15/reference/tessen.md
  content/sensu-go/5.16/guides/troubleshooting.md
  content/sensu-go/5.16/reference/tessen.md
Labels: errata, ready for review

#2017 Add datastore API article
  content/sensu-go/5.12/api/datastore.md
  content/sensu-go/5.13/api/datastore.md
  content/sensu-go/5.14/api/datastore.md
  content/sensu-go/5.15/api/datastore.md
  content/sensu-go/5.16/api/datastore.md
Labels: ready for review, update

#1996 Copy edit 5.16 API articles, H through V
  content/sensu-go/5.16/api/handlers.md
  content/sensu-go/5.16/api/health.md
  content/sensu-go/5.16/api/hooks.md
  content/sensu-go/5.16/api/license.md
  content/sensu-go/5.16/api/metrics.md
  content/sensu-go/5.16/api/mutators.md
  content/sensu-go/5.16/api/namespaces.md
  content/sensu-go/5.16/api/role-bindings.md
  content/sensu-go/5.16/api/roles.md
  content/sensu-go/5.16/api/silenced.md
  content/sensu-go/5.16/api/tessen.md
  content/sensu-go/5.16/api/users.md
  content/sensu-go/5.16/api/version.md
Labels: improvement, ready for review

#1993 Copy edit 5.16 API articles, A through F
  content/sensu-go/5.16/api/apikeys.md
  content/sensu-go/5.16/api/assets.md
  content/sensu-go/5.16/api/auth.md
  content/sensu-go/5.16/api/authproviders.md
  content/sensu-go/5.16/api/checks.md
  content/sensu-go/5.16/api/cluster-role-bindings.md
  content/sensu-go/5.16/api/cluster-roles.md
  content/sensu-go/5.16/api/cluster.md
  content/sensu-go/5.16/api/datastore.md
  content/sensu-go/5.16/api/entities.md
  content/sensu-go/5.16/api/events.md
  content/sensu-go/5.16/api/federation.md
  content/sensu-go/5.16/api/filters.md
  content/sensu-go/5.16/api/overview.md
Labels: improvement, ready for review

#2011 Add solaris package section to binary distro page
  content/sensu-go/5.16/installation/verify.md
Labels: ready for review

#2020 Add solaris info in Installation docs
  content/sensu-go/5.16/installation/platforms.md
  content/sensu-go/5.16/installation/verify.md
Labels: ready for review

#1986 Copy edit all 5.16 Installation section articles
  content/sensu-go/5.16/installation/auth.md
  content/sensu-go/5.16/installation/configuration-management.md
  content/sensu-go/5.16/installation/install-sensu.md
  content/sensu-go/5.16/installation/platforms.md
  content/sensu-go/5.16/installation/plugins.md
  content/sensu-go/5.16/installation/recommended-hardware.md
  content/sensu-go/5.16/installation/upgrade.md
  content/sensu-go/5.16/installation/verify.md
Labels: improvement, ready for review

#2008 Update docs with default admin credentials to explain init
  content/sensu-go/5.16/api/authproviders.md
  content/sensu-go/5.16/getting-started/learn-sensu.md
  content/sensu-go/5.16/getting-started/prometheus-metrics.md
  content/sensu-go/5.16/getting-started/sample-app.md
  content/sensu-go/5.16/installation/auth.md
  content/sensu-go/5.16/installation/install-sensu.md
  content/sensu-go/5.16/reference/rbac.md
  content/sensu-go/5.16/sensuctl/quickstart.md
  content/sensu-go/5.16/sensuctl/reference.md
Labels: errata, ready for review

#2021 Add list of critical success factors for etcd replication
  content/sensu-go/5.15/reference/etcdreplicators.md
  content/sensu-go/5.16/reference/etcdreplicators.md
Labels: improvement, ready for review, security

#1983 Copy edit 5.16 articles in Getting Started section
  content/sensu-go/5.16/getting-started/_index.md
  content/sensu-go/5.16/getting-started/demo.md
  content/sensu-go/5.16/getting-started/enterprise.md
  content/sensu-go/5.16/getting-started/faq.md
  content/sensu-go/5.16/getting-started/get-started.md
  content/sensu-go/5.16/getting-started/glossary.md
  content/sensu-go/5.16/getting-started/learn-sensu.md
  content/sensu-go/5.16/getting-started/media.md
  content/sensu-go/5.16/getting-started/prometheus-metrics.md
  content/sensu-go/5.16/getting-started/sample-app.md
  content/sensu-go/5.16/getting-started/sandbox.md
  content/sensu-go/5.16/getting-started/tutorial.md
  content/sensu-go/5.16/getting-started/versions.md
Labels: improvement, ready for review

#1999 Copy edit 5.16 reference articles, A through F
  content/sensu-go/5.16/reference/_index.md
  content/sensu-go/5.16/reference/agent.md
  content/sensu-go/5.16/reference/apikeys.md
  content/sensu-go/5.16/reference/assets.md
  content/sensu-go/5.16/reference/backend.md
  content/sensu-go/5.16/reference/checks.md
  content/sensu-go/5.16/reference/datastore.md
  content/sensu-go/5.16/reference/entities.md
  content/sensu-go/5.16/reference/etcdreplicators.md
  content/sensu-go/5.16/reference/events.md
  content/sensu-go/5.16/reference/filters.md
Labels: improvement, ready for review

#2000 Copy edit 5.16 reference articles H through end
  content/sensu-go/5.16/reference/handlers.md
  content/sensu-go/5.16/reference/hooks.md
  content/sensu-go/5.16/reference/license.md
  content/sensu-go/5.16/reference/mutators.md
  content/sensu-go/5.16/reference/rbac.md
  content/sensu-go/5.16/reference/sensu-query-expressions.md
  content/sensu-go/5.16/reference/silencing.md
  content/sensu-go/5.16/reference/tessen.md
  content/sensu-go/5.16/reference/tokens.md
Labels: improvement, ready for review

#2032 Release notes for 5.16.1
  content/sensu-go/5.16/release-notes.md
Labels: ready for review

#2010 Copy edit 5.16 guides
  content/sensu-go/5.16/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.16/guides/clustering.md
  content/sensu-go/5.16/guides/contact-routing.md
  content/sensu-go/5.16/guides/create-read-only-user.md
  content/sensu-go/5.16/guides/deploying.md
  content/sensu-go/5.16/guides/enrich-events-with-hooks.md
  content/sensu-go/5.16/guides/extract-metrics-with-checks.md
  content/sensu-go/5.16/guides/influx-db-metric-handler.md
  content/sensu-go/5.16/guides/install-check-executables-with-assets.md
  content/sensu-go/5.16/guides/monitor-external-resources.md
  content/sensu-go/5.16/guides/monitor-server-resources.md
  content/sensu-go/5.16/guides/plan-maintenance.md
  content/sensu-go/5.16/guides/reduce-alert-fatigue.md
  content/sensu-go/5.16/guides/scale-event-storage.md
  content/sensu-go/5.16/guides/securing-sensu.md
  content/sensu-go/5.16/guides/send-slack-alerts.md
  content/sensu-go/5.16/guides/systemd-logs.md
  content/sensu-go/5.16/guides/troubleshooting.md
  content/sensu-go/5.16/guides/use-apikey-feature.md
Labels: improvement, ready for review

#2037 Add "backend must be running" to sensu-backend init instructions
  content/sensu-go/5.16/installation/install-sensu.md
  content/sensu-go/5.16/reference/backend.md
Labels: ready for review, update

#2016 Add info about using env vars in Agent reference
  content/sensu-go/5.16/reference/agent.md
Labels: ready for review, update

#1959 Add federation guide
  content/sensu-go/5.15/guides/use-federation.md
  content/sensu-go/5.15/reference/backend.md
  content/sensu-go/5.16/guides/use-federation.md
  static/images/federation-guide-diagram.png
  static/images/federation-switcher-animated.gif
Labels: in progress, new doc

#2040 Add doc updates and release notes for Core 1.9
  content/sensu-core/1.9/changelog.md
  content/sensu-core/1.9/reference/checks.md
  content/sensu-core/1.9/reference/transport.md
Labels: ready for review

#2043 Promote Core 1.9 to latest
  config.toml
  layouts/partials/footer_js.html
  static.json
  themes/hugo-material-docs/layouts/partials/footer_js.html
Labels: ready for review

#2049 Add global meta tag for Algolia Docsearch
  layouts/partials/head.html
Labels: ready for review
