Repository sensu/sensu-docs, pull requests merged in 2020-04, with the labels that each got.

#2328 Add timeout query param to health and cluster API description tables
  content/sensu-go/5.19/api/cluster.md
  content/sensu-go/5.19/api/health.md
Labels: ready for review, update

#2331 Add PowerShell example with -f flag to check reference
  content/sensu-go/5.19/reference/checks.md
Labels: ready for review, update

#2326 Correct sensu-backend start command in clustering guide
  content/sensu-go/5.16/guides/clustering.md
  content/sensu-go/5.17/guides/clustering.md
  content/sensu-go/5.18/guides/clustering.md
  content/sensu-go/5.19/guides/clustering.md
Labels: errata, ready for review

#2334 Add realistic values for executed field in events API doc
  content/sensu-go/5.16/api/events.md
  content/sensu-go/5.16/reference/events.md
  content/sensu-go/5.17/api/events.md
  content/sensu-go/5.17/reference/events.md
  content/sensu-go/5.18/api/events.md
  content/sensu-go/5.18/reference/events.md
  content/sensu-go/5.19/api/events.md
  content/sensu-go/5.19/reference/events.md
Labels: improvement, ready for review

#2343 Fix typo in troubleshooting front matter description
  content/sensu-go/5.16/guides/troubleshooting.md
  content/sensu-go/5.17/guides/troubleshooting.md
  content/sensu-go/5.18/guides/troubleshooting.md
  content/sensu-go/5.19/guides/troubleshooting.md
Labels: errata

#2341 Add prune API page for 5.19
  content/sensu-go/5.19/api/prune.md
  content/sensu-go/5.19/sensuctl/reference.md
Labels: new doc, ready for review

#2234 Add agent mTLS auth explanation for secrets docs
  content/sensu-go/5.18/guides/secrets-management.md
  content/sensu-go/5.18/guides/securing-sensu.md
  content/sensu-go/5.18/reference/secrets-providers.md
  content/sensu-go/5.18/reference/secrets.md
  content/sensu-go/5.19/guides/secrets-management.md
  content/sensu-go/5.19/guides/securing-sensu.md
  content/sensu-go/5.19/reference/secrets-providers.md
  content/sensu-go/5.19/reference/secrets.md
Labels: improvement, ready for review

#2353 Correct Docker Compose volume in backend installation instructions
  content/sensu-go/5.16/installation/install-sensu.md
  content/sensu-go/5.17/installation/install-sensu.md
  content/sensu-go/5.18/installation/install-sensu.md
  content/sensu-go/5.19/installation/install-sensu.md
Labels: errata, ready for review

#2263 Enterprise EOL: Update Enterprise and Enterprise Dashboard banners and notes about EOL
  content/sensu-enterprise-dashboard/2.10/_index.md
  content/sensu-enterprise-dashboard/2.11/_index.md
  content/sensu-enterprise-dashboard/2.12/_index.md
  content/sensu-enterprise-dashboard/2.13/_index.md
  content/sensu-enterprise-dashboard/2.14/_index.md
  content/sensu-enterprise-dashboard/2.15/_index.md
  content/sensu-enterprise-dashboard/2.16/_index.md
  content/sensu-enterprise-dashboard/2.9/_index.md
  content/sensu-enterprise/2.6/_index.md
  content/sensu-enterprise/2.7/_index.md
  content/sensu-enterprise/2.8/_index.md
  content/sensu-enterprise/3.0/_index.md
  content/sensu-enterprise/3.1/_index.md
  content/sensu-enterprise/3.2/_index.md
  content/sensu-enterprise/3.3/_index.md
  content/sensu-enterprise/3.4/_index.md
  content/sensu-enterprise/3.5/_index.md
  content/sensu-enterprise/3.6/_index.md
  content/sensu-enterprise/3.7/_index.md
  layouts/partials/eolSection.html
Labels: ready for review

#2182 Improve Sensu query expressions doc and add label/annotation examples
  content/sensu-go/5.16/reference/sensu-query-expressions.md
  content/sensu-go/5.17/reference/sensu-query-expressions.md
  content/sensu-go/5.18/reference/sensu-query-expressions.md
  content/sensu-go/5.19/reference/sensu-query-expressions.md
Labels: help wanted, improvement

#2362 Fix order of Docker and Docker Compose code elements for backend installation
  content/sensu-go/5.17/installation/install-sensu.md
  content/sensu-go/5.17/reference/backend.md
  content/sensu-go/5.18/installation/install-sensu.md
  content/sensu-go/5.18/reference/backend.md
  content/sensu-go/5.19/installation/install-sensu.md
  content/sensu-go/5.19/reference/backend.md
Labels: errata, ready for review

#2352 Update 404 page
  config.toml
  layouts/404.html
  layouts/_default/base-for-directory-listing.html
  layouts/_default/product-platforms.html
  layouts/_default/product-versions.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/footer_js.html
  layouts/partials/head.html
  static/stylesheets/scss/_layout.scss
  static/stylesheets/scss/_search.scss
Labels: ready for review

#2261 [Do not merge] Enterprise EOL: Replace tiles on docs index page
  layouts/index.html
Labels: ready for review

#2274 Enterprise EOL: Remove sensu-core links from Go docs
  content/sensu-go/5.16/installation/upgrade.md
  content/sensu-go/5.16/reference/agent.md
  content/sensu-go/5.16/reference/checks.md
  content/sensu-go/5.17/installation/upgrade.md
  content/sensu-go/5.17/reference/agent.md
  content/sensu-go/5.17/reference/checks.md
  content/sensu-go/5.18/installation/upgrade.md
  content/sensu-go/5.18/reference/agent.md
  content/sensu-go/5.18/reference/checks.md
  content/sensu-go/5.19/installation/upgrade.md
  content/sensu-go/5.19/reference/agent.md
  content/sensu-go/5.19/reference/checks.md
Labels: ready for review

#2374 Fix search bug introduced by #2352
  config.toml
  layouts/404.html
  layouts/_default/base-for-directory-listing.html
  layouts/_default/product-platforms.html
  layouts/_default/product-versions.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/footer_js.html
  layouts/partials/head.html
  static/stylesheets/scss/_layout.scss
  static/stylesheets/scss/_search.scss
Labels: ready for review

#2369 Update timeout query param in cluster and health API doc for 5.19.1
  content/sensu-go/5.19/api/cluster.md
  content/sensu-go/5.19/api/health.md
Labels: ready for review, update

#2357 Add changelog for Enterprise 3.8.0
  content/sensu-enterprise/3.8/changelog.md
Labels: in progress

#2356 Fix scroll jump bug when toggling languages in code blocks
  layouts/partials/footer_js.html
Labels: ready for review

#2348 Clarify syntax in all filtering documentation
  content/sensu-go/5.19/api/overview.md
  content/sensu-go/5.19/dashboard/filtering.md
  content/sensu-go/5.19/sensuctl/reference.md
  content/sensu-go/5.20/api/overview.md
  content/sensu-go/5.20/dashboard/filtering.md
  content/sensu-go/5.20/sensuctl/reference.md
Labels: ready for review, update

#2279 Improve env vars explanations in agent and backend references
  content/sensu-go/5.18/reference/agent.md
  content/sensu-go/5.18/reference/backend.md
  content/sensu-go/5.19/reference/agent.md
  content/sensu-go/5.19/reference/backend.md
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.20/reference/backend.md
Labels: improvement, ready for review, update

#2380 Add event.is_silenced and event.check.is_silenced field selectors
  content/sensu-go/5.20/api/overview.md
Labels: ready for review, update

#2388 Add explanation and example for quoted strings in token reference
  content/sensu-go/5.20/reference/tokens.md
Labels: ready for review, update

#2389 Update license response info to include entity count and limit
  content/sensu-go/5.20/api/license.md
  content/sensu-go/5.20/reference/license.md
Labels: update

#2384 Add labels and annotations flags to config options in backend reference
  content/sensu-go/5.20/reference/backend.md
Labels: ready for review, update

#2396 Add release notes for 5.19.2
  content/sensu-go/5.19/release-notes.md
Labels: ready for review, update

#2401 Add Ubuntu 19.10 and 20.04 to supported platforms page
  content/sensu-go/5.19/installation/platforms.md
  content/sensu-go/5.20/installation/platforms.md
Labels: ready for review, update

#2398 Add max_conn_lifetime and max_idle_conns params to datastore API and reference docs
  content/sensu-go/5.19/reference/datastore.md
  content/sensu-go/5.20/api/datastore.md
  content/sensu-go/5.20/reference/datastore.md
Labels: ready for review, update

#2402 Update version and build numbers for 5.19.2
  content/sensu-go/5.19/installation/install-sensu.md
  content/sensu-go/5.19/installation/verify.md
Labels: ready for review, update

#2391 Add processes flag and field for agent, entities, and events
  content/sensu-go/5.20/api/entities.md
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.20/reference/entities.md
  content/sensu-go/5.20/reference/events.md
  content/sensu-go/5.20/reference/tokens.md
Labels: ready for review, update

#2406 Add log level increment commands
  content/sensu-go/5.20/guides/troubleshooting.md
Labels: ready for review, update

#2409 Add Lizy image to 404 page
  layouts/404.html
  static/images/idle-lizy.png
  static/stylesheets/scss/_layout.scss
Labels: enhancement

#2413 Fix TOC in Tessen reference docs
  content/sensu-go/5.16/reference/tessen.md
  content/sensu-go/5.17/reference/tessen.md
  content/sensu-go/5.18/reference/tessen.md
  content/sensu-go/5.19/reference/tessen.md
  content/sensu-go/5.20/reference/tessen.md
Labels: errata
