Repository sensu/sensu-docs, pull requests merged in 2020-08, with the labels that each got.

#2664 Fix Authorization: KEY to Authorization: Key in API keys api doc
  content/sensu-go/5.20/api/apikeys.md
  content/sensu-go/5.21/api/apikeys.md
  content/sensu-go/6.0/api/apikeys.md
Labels: errata

#2668 Update etcd and Sensu version numbers in version API doc
  content/sensu-go/6.0/api/version.md
Labels: ready for review, update

#2641 Add Docker-specific defaults for agent and backend environment variables
  content/sensu-go/6.0/reference/agent.md
  content/sensu-go/6.0/reference/backend.md
Labels: ready for review

#2677 update the entities reference documentation
  content/sensu-go/6.0/reference/entities.md
Labels: update

#2669 Correct etcd-client-urls to space-delimited list
  content/sensu-go/5.19/operations/deploy-sensu/cluster-sensu.md
  content/sensu-go/5.20/operations/deploy-sensu/cluster-sensu.md
  content/sensu-go/5.21/operations/deploy-sensu/cluster-sensu.md
  content/sensu-go/6.0/operations/deploy-sensu/cluster-sensu.md
Labels: errata, ready for review

#2683 Add amd64 CGO binaries to platforms page
  content/sensu-go/5.21/platforms.md
  content/sensu-go/6.0/platforms.md
Labels: update

#2684 Add notes to clarify contents of binaries for each arch
  content/sensu-go/5.21/platforms.md
  content/sensu-go/6.0/platforms.md
Labels: improvement

#2660 Add note to explain response codes vs response body for health API endpoint
  content/sensu-go/5.19/api/health.md
  content/sensu-go/5.20/api/health.md
  content/sensu-go/5.21/api/health.md
  content/sensu-go/6.0/api/health.md
Labels: improvement, ready for review

#2686 Fix redirects for create-a-read-only-user
  static.json
Labels: bug

#2678 Add back up and recover documentation in the sensuctl category
  content/sensu-go/5.19/operations/deploy-sensu/install-sensu.md
  content/sensu-go/5.19/sensuctl/back-up-recover.md
  content/sensu-go/5.19/sensuctl/create-manage-resources.md
  content/sensu-go/5.20/operations/deploy-sensu/install-sensu.md
  content/sensu-go/5.20/sensuctl/back-up-recover.md
  content/sensu-go/5.20/sensuctl/create-manage-resources.md
  content/sensu-go/5.21/operations/deploy-sensu/install-sensu.md
  content/sensu-go/5.21/sensuctl/back-up-recover.md
  content/sensu-go/5.21/sensuctl/create-manage-resources.md
  content/sensu-go/6.0/operations/deploy-sensu/install-sensu.md
  content/sensu-go/6.0/operations/maintain-sensu/upgrade.md
  content/sensu-go/6.0/sensuctl/back-up-recover.md
  content/sensu-go/6.0/sensuctl/create-manage-resources.md
Labels: new doc, ready for review

#2688 Clarify health API HTTP response codes and add unhealthy example
  content/sensu-go/5.19/api/health.md
  content/sensu-go/5.19/reference/health.md
  content/sensu-go/5.20/api/health.md
  content/sensu-go/5.20/reference/health.md
  content/sensu-go/5.21/api/health.md
  content/sensu-go/5.21/reference/health.md
  content/sensu-go/6.0/api/health.md
  content/sensu-go/6.0/reference/health.md
Labels: errata, improvement, ready for review
