Repository sensu/sensu-docs, pull requests merged in 2020-06, with the labels that each got.

#2387 Add logrotate example to backend reference
  content/sensu-go/5.17/guides/systemd-logs.md
  content/sensu-go/5.17/reference/backend.md
  content/sensu-go/5.18/guides/systemd-logs.md
  content/sensu-go/5.18/reference/backend.md
  content/sensu-go/5.19/guides/systemd-logs.md
  content/sensu-go/5.19/reference/backend.md
  content/sensu-go/5.20/guides/systemd-logs.md
  content/sensu-go/5.20/reference/backend.md
Labels: ready for review, update

#2484 Add use cases for entity system attributes in asset reference
  content/sensu-go/5.17/reference/assets.md
  content/sensu-go/5.18/reference/assets.md
  content/sensu-go/5.19/reference/assets.md
  content/sensu-go/5.20/reference/assets.md
Labels: improvement

#2486 Allow list configuration section edits
  content/sensu-go/5.17/reference/agent.md
  content/sensu-go/5.18/reference/agent.md
  content/sensu-go/5.19/reference/agent.md
  content/sensu-go/5.19/reference/assets.md
  content/sensu-go/5.19/release-notes.md
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.20/reference/assets.md
  content/sensu-go/5.20/release-notes.md
  content/sensu-go/5.21/reference/agent.md
  content/sensu-go/5.21/release-notes.md
Labels: errata, ready for review

#2493 Fix link to API page in 5.17, 5.18, 5.19. and 5.20
  content/sensu-go/5.17/reference/license.md
  content/sensu-go/5.18/reference/license.md
  content/sensu-go/5.19/reference/license.md
  content/sensu-go/5.20/reference/license.md
Labels: errata

#2465 Add searches API and reference documentation
  content/sensu-go/5.19/api/searches.md
  content/sensu-go/5.19/reference/searches.md
  content/sensu-go/5.20/api/searches.md
  content/sensu-go/5.20/reference/searches.md
  content/sensu-go/5.21/api/searches.md
  content/sensu-go/5.21/reference/searches.md
Labels: new doc, ready for review

#2490 Change agent default log level to info
  content/sensu-go/5.20/guides/troubleshooting.md
  content/sensu-go/5.21/guides/troubleshooting.md
  content/sensu-go/5.21/reference/agent.md
Labels: ready for review, update

#2482 Add authentication note to API docs and clarify auth content in API overview
  content/sensu-go/5.20/api/apikeys.md
  content/sensu-go/5.20/api/assets.md
  content/sensu-go/5.20/api/authproviders.md
  content/sensu-go/5.20/api/checks.md
  content/sensu-go/5.20/api/cluster-role-bindings.md
  content/sensu-go/5.20/api/cluster-roles.md
  content/sensu-go/5.20/api/cluster.md
  content/sensu-go/5.20/api/datastore.md
  content/sensu-go/5.20/api/entities.md
  content/sensu-go/5.20/api/events.md
  content/sensu-go/5.20/api/federation.md
  content/sensu-go/5.20/api/filters.md
  content/sensu-go/5.20/api/handlers.md
  content/sensu-go/5.20/api/hooks.md
  content/sensu-go/5.20/api/license.md
  content/sensu-go/5.20/api/mutators.md
  content/sensu-go/5.20/api/namespaces.md
  content/sensu-go/5.20/api/overview.md
  content/sensu-go/5.20/api/prune.md
  content/sensu-go/5.20/api/role-bindings.md
  content/sensu-go/5.20/api/roles.md
  content/sensu-go/5.20/api/searches.md
  content/sensu-go/5.20/api/secrets.md
  content/sensu-go/5.20/api/silenced.md
  content/sensu-go/5.20/api/tessen.md
  content/sensu-go/5.20/api/users.md
  content/sensu-go/5.20/api/webconfig.md
  content/sensu-go/5.21/api/apikeys.md
  content/sensu-go/5.21/api/assets.md
  content/sensu-go/5.21/api/authproviders.md
  content/sensu-go/5.21/api/checks.md
  content/sensu-go/5.21/api/cluster-role-bindings.md
  content/sensu-go/5.21/api/cluster-roles.md
  content/sensu-go/5.21/api/cluster.md
  content/sensu-go/5.21/api/datastore.md
  content/sensu-go/5.21/api/entities.md
  content/sensu-go/5.21/api/events.md
  content/sensu-go/5.21/api/federation.md
  content/sensu-go/5.21/api/filters.md
  content/sensu-go/5.21/api/handlers.md
  content/sensu-go/5.21/api/hooks.md
  content/sensu-go/5.21/api/license.md
  content/sensu-go/5.21/api/mutators.md
  content/sensu-go/5.21/api/namespaces.md
  content/sensu-go/5.21/api/overview.md
  content/sensu-go/5.21/api/prune.md
  content/sensu-go/5.21/api/role-bindings.md
  content/sensu-go/5.21/api/roles.md
  content/sensu-go/5.21/api/searches.md
  content/sensu-go/5.21/api/secrets.md
  content/sensu-go/5.21/api/silenced.md
  content/sensu-go/5.21/api/tessen.md
  content/sensu-go/5.21/api/users.md
  content/sensu-go/5.21/api/webconfig.md
Labels: improvement, ready for review

#2500 Fix 404 errors due to info arch work this week
  content/sensu-go/5.17/commercial.md
  content/sensu-go/5.17/getting-started/faq.md
  content/sensu-go/5.17/getting-started/get-started.md
  content/sensu-go/5.17/getting-started/versions.md
  content/sensu-go/5.18/commercial.md
  content/sensu-go/5.18/getting-started/faq.md
  content/sensu-go/5.18/getting-started/get-started.md
  content/sensu-go/5.18/getting-started/versions.md
  content/sensu-go/5.18/guides/generate-certificates.md
  content/sensu-go/5.19/commercial.md
  content/sensu-go/5.19/getting-started/get-started.md
  content/sensu-go/5.19/getting-started/versions.md
  content/sensu-go/5.19/guides/generate-certificates.md
  content/sensu-go/5.20/commercial.md
  content/sensu-go/5.20/getting-started/faq.md
  content/sensu-go/5.20/getting-started/get-started.md
  content/sensu-go/5.20/getting-started/versions.md
  content/sensu-go/5.20/guides/generate-certificates.md
  content/sensu-go/5.21/commercial.md
  content/sensu-go/5.21/getting-started/faq.md
  content/sensu-go/5.21/getting-started/get-started.md
  content/sensu-go/5.21/getting-started/versions.md
  content/sensu-go/5.21/guides/generate-certificates.md
Labels: errata

#2492 Update tabular license response title with examples of new format
  content/sensu-go/5.21/reference/license.md
Labels: ready for review, update

#2510 Move max_retries, timeout, and rate_limiter parameters to client attributes section
  content/sensu-go/5.17/reference/secrets-providers.md
  content/sensu-go/5.18/reference/secrets-providers.md
  content/sensu-go/5.19/reference/secrets-providers.md
  content/sensu-go/5.20/reference/secrets-providers.md
  content/sensu-go/5.21/reference/secrets-providers.md
Labels: errata

#2494 Add token subs for asset path to token reference
  content/sensu-go/5.21/reference/assets.md
  content/sensu-go/5.21/reference/checks.md
Labels: new feature, ready for review

#2512 Shorten tables on platforms.md page
  content/sensu-go/5.17/platforms.md
  content/sensu-go/5.18/platforms.md
  content/sensu-go/5.19/platforms.md
  content/sensu-go/5.20/platforms.md
  content/sensu-go/5.21/platforms.md
Labels: enhancement

#2511 Add OpenSSL/FIPS flags to agent and backend references
  content/sensu-go/5.21/reference/agent.md
  content/sensu-go/5.21/reference/backend.md
Labels: new feature, ready for review

#2520 Remove notes about TCP rather than UDP on Windows systems for statsd
  content/sensu-go/5.17/getting-started/faq.md
  content/sensu-go/5.17/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.17/reference/agent.md
  content/sensu-go/5.18/getting-started/faq.md
  content/sensu-go/5.18/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.18/reference/agent.md
  content/sensu-go/5.19/getting-started/faq.md
  content/sensu-go/5.19/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.19/installation/upgrade.md
  content/sensu-go/5.19/reference/agent.md
  content/sensu-go/5.20/getting-started/faq.md
  content/sensu-go/5.20/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.20/installation/upgrade.md
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.21/getting-started/faq.md
  content/sensu-go/5.21/guides/aggregate-metrics-statsd.md
  content/sensu-go/5.21/installation/upgrade.md
  content/sensu-go/5.21/reference/agent.md
Labels: errata, ready for review

#2532 Fix katacoda styles (make full width)
  static/stylesheets/scss/_layout.scss
Labels: ready for review

#2543 Add web UI management info for events, entities, and silences
  content/sensu-go/5.18/web-ui/view-manage-resources.md
  content/sensu-go/5.19/web-ui/view-manage-resources.md
  content/sensu-go/5.20/web-ui/view-manage-resources.md
  content/sensu-go/5.21/web-ui/view-manage-resources.md
Labels: ready for review, update

#2546 Move sensu_agent_version to top level of spec in entity definition examples
  content/sensu-go/5.18/reference/entities.md
  content/sensu-go/5.19/reference/entities.md
  content/sensu-go/5.20/reference/entities.md
  content/sensu-go/5.21/reference/entities.md
Labels: errata, ready for review

#2516 Remove sensuctl env from top of env var usage examples
  content/sensu-go/5.18/sensuctl/reference.md
  content/sensu-go/5.19/sensuctl/reference.md
  content/sensu-go/5.20/sensuctl/reference.md
  content/sensu-go/5.21/sensuctl/reference.md
Labels: errata, ready for review

#2542 Update note about keepalive monitoring for proxy entities
  content/sensu-go/5.18/reference/agent.md
  content/sensu-go/5.19/reference/agent.md
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.21/reference/agent.md
Labels: errata, ready for review

#2560 Fix 404s introduced in sensuctl and api heading changes
  content/sensu-go/5.18/guides/plan-maintenance.md
  content/sensu-go/5.18/sensuctl/create-manage-resources.md
  content/sensu-go/5.18/versions.md
  content/sensu-go/5.19/sensuctl/create-manage-resources.md
  content/sensu-go/5.19/versions.md
  content/sensu-go/5.20/reference/webconfig.md
  content/sensu-go/5.20/versions.md
  content/sensu-go/5.21/reference/webconfig.md
  content/sensu-go/5.21/versions.md
Labels: errata

#2561 Add support for multi-level navigation nesting
  layouts/partials/nav.html
Labels: ready for review

#2565 Update users API doc to add reset_password endpoint and clarify PUT /password endpoint
  content/sensu-go/5.21/api/users.md
Labels: ready for review, update

#2570 Change federation switcher gif at the end of the federation guide
  static/images/federation-switcher-animated.gif
Labels: update

#2574 Remove link in 5.21.0 release notes for FIPS OpenSSL binaries
  content/sensu-go/5.21/release-notes.md
Labels: improvement

#2557 Remove integrations section from platforms and distributions page
  content/sensu-go/5.18/platforms.md
  content/sensu-go/5.19/platforms.md
  content/sensu-go/5.20/platforms.md
  content/sensu-go/5.21/platforms.md
Labels: improvement, ready for review

#2569 Add silenced key to spec description table in events reference doc
  content/sensu-go/5.18/reference/events.md
  content/sensu-go/5.19/reference/events.md
  content/sensu-go/5.20/reference/events.md
  content/sensu-go/5.21/reference/events.md
Labels: ready for review, update

#2566 Rework the end of the Install Sensu guide
  content/sensu-go/5.18/installation/install-sensu.md
  content/sensu-go/5.19/installation/install-sensu.md
  content/sensu-go/5.20/installation/install-sensu.md
  content/sensu-go/5.21/installation/install-sensu.md
Labels: improvement, ready for review, update

#2577 Add database clarification to Install Sensu doc
  content/sensu-go/5.18/installation/install-sensu.md
  content/sensu-go/5.19/installation/install-sensu.md
  content/sensu-go/5.20/installation/install-sensu.md
  content/sensu-go/5.21/installation/install-sensu.md
Labels: improvement

#2579 Remove note about subscription matching for proxy entities in Entities reference
  content/sensu-go/5.18/reference/entities.md
  content/sensu-go/5.19/reference/entities.md
  content/sensu-go/5.20/reference/entities.md
  content/sensu-go/5.21/reference/entities.md
Labels: errata
