Repository sensu/sensu-docs, pull requests merged in 2020-09, with the labels that each got.

#2701 Add supported OS versions for binary distributions
  content/sensu-go/5.19/platforms.md
  content/sensu-go/5.20/platforms.md
  content/sensu-go/5.21/platforms.md
  content/sensu-go/6.0/platforms.md
Labels: ready for review, update

#2703 Update resource names and lists for sensuctl dump and sensuctl prune
  content/sensu-go/5.19/sensuctl/back-up-recover.md
  content/sensu-go/5.19/sensuctl/create-manage-resources.md
  content/sensu-go/5.20/sensuctl/back-up-recover.md
  content/sensu-go/5.20/sensuctl/create-manage-resources.md
  content/sensu-go/5.21/sensuctl/back-up-recover.md
  content/sensu-go/5.21/sensuctl/create-manage-resources.md
  content/sensu-go/6.0/sensuctl/back-up-recover.md
  content/sensu-go/6.0/sensuctl/create-manage-resources.md
Labels: ready for review, update

#2702 Update instructions for creating an OIDC app
  content/sensu-go/5.19/operations/control-access/auth.md
  content/sensu-go/5.20/operations/control-access/auth.md
  content/sensu-go/5.21/operations/control-access/auth.md
  content/sensu-go/6.0/operations/control-access/auth.md
Labels: ready for review, update

#2710 Remove MIPS packages from platforms page
  content/sensu-go/6.0/platforms.md
Labels: errata, ready for review

#2711 Add observability pipeline notice to Sensu Go 5.x 404 page
  layouts/404.html
  static/js/toc.js
Labels: ready for review

#2725 Fix `typeListing` shortcode to work for any 6.x Reference Index
  content/sensu-go/6.0/reference/_index.md
  content/sensu-go/6.1/reference/_index.md
  layouts/shortcodes/typeListing.html
  layouts/shortcodes/typeListing60.html
  layouts/shortcodes/typeListing61.html
  offline/shortcodes/typeListing.html
  offline/shortcodes/typeListing60.html
  offline/shortcodes/typeListing61.html
Labels: ready for review

#2727 Fix HTTP response codes for create entities and events
  content/sensu-go/5.19/api/entities.md
  content/sensu-go/5.19/api/events.md
  content/sensu-go/5.20/api/entities.md
  content/sensu-go/5.20/api/events.md
  content/sensu-go/5.21/api/entities.md
  content/sensu-go/5.21/api/events.md
  content/sensu-go/6.0/api/entities.md
  content/sensu-go/6.0/api/events.md
  content/sensu-go/6.1/api/entities.md
  content/sensu-go/6.1/api/events.md
Labels: errata

#2723 Add prometheus_text as an output_metric_format option
  content/sensu-go/6.1/observability-pipeline/observe-filter/filters.md
  content/sensu-go/6.1/observability-pipeline/observe-schedule/checks.md
  content/sensu-go/6.1/observability-pipeline/observe-schedule/collect-metrics-with-checks.md
Labels: ready for review

#2728 Add types query parameter
  content/sensu-go/6.1/api/authproviders.md
  content/sensu-go/6.1/api/secrets.md
Labels: ready for review

#2726 Add output_metric_tags
  content/sensu-go/6.1/api/checks.md
  content/sensu-go/6.1/api/events.md
  content/sensu-go/6.1/migrate.md
  content/sensu-go/6.1/observability-pipeline/observe-filter/reduce-alert-fatigue.md
  content/sensu-go/6.1/observability-pipeline/observe-schedule/checks.md
  content/sensu-go/6.1/observability-pipeline/observe-schedule/collect-metrics-with-checks.md
  content/sensu-go/6.1/observability-pipeline/observe-schedule/tokens.md
  content/sensu-go/6.1/operations/maintain-sensu/troubleshoot.md
  content/sensu-go/6.1/operations/monitor-sensu/monitor-sensu-with-sensu.md
Labels: ready for review

#2733 Update the script for adding a new version to update interactive tutorial links
  scripts/new-docs-version.sh
Labels: enhancement, ready for review

#2736 Add agent flags re: backend handshake and heartbeat
  content/sensu-go/5.19/reference/agent.md
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.21/reference/agent.md
  content/sensu-go/6.0/observability-pipeline/observe-schedule/agent.md
  content/sensu-go/6.1/observability-pipeline/observe-schedule/agent.md
Labels: ready for review, update

#2704 Add legacy/other platforms information
  content/sensu-go/5.19/platforms.md
  content/sensu-go/5.20/platforms.md
  content/sensu-go/5.21/platforms.md
  content/sensu-go/6.0/platforms.md
  content/sensu-go/6.1/platforms.md
Labels: ready for review, update

#2738 Clarify pq library support for dsn spec attribute
  content/sensu-go/5.19/reference/datastore.md
  content/sensu-go/5.20/reference/datastore.md
  content/sensu-go/5.21/reference/datastore.md
  content/sensu-go/6.0/operations/deploy-sensu/datastore.md
  content/sensu-go/6.1/operations/deploy-sensu/datastore.md
Labels: errata, ready for review

#2605 Add information about subscriptions and agent-backend interaction to architecture overview
  content/sensu-go/5.19/operations/deploy-sensu/install-sensu.md
  content/sensu-go/5.20/operations/deploy-sensu/install-sensu.md
  content/sensu-go/5.21/operations/deploy-sensu/install-sensu.md
  content/sensu-go/6.0/operations/deploy-sensu/install-sensu.md
  content/sensu-go/6.1/operations/deploy-sensu/install-sensu.md
Labels: improvement, ready for review

#2722 Add Vault KV v2 format and restore custom secret paths
  content/sensu-go/6.1/operations/manage-secrets/secrets-management.md
  content/sensu-go/6.1/operations/manage-secrets/secrets.md
Labels: ready for review

#2749 Add troubleshooting info for version discovery on unsupported Linux platforms
  content/sensu-go/5.19/operations/maintain-sensu/troubleshoot.md
  content/sensu-go/5.20/operations/maintain-sensu/troubleshoot.md
  content/sensu-go/5.21/operations/maintain-sensu/troubleshoot.md
  content/sensu-go/6.0/operations/maintain-sensu/troubleshoot.md
  content/sensu-go/6.1/operations/maintain-sensu/troubleshoot.md
Labels: improvement, ready for review

#2742 Add event-based handler templates documentation
  content/sensu-go/5.19/guides/handler-templates.md
  content/sensu-go/5.20/guides/handler-templates.md
  content/sensu-go/5.21/guides/handler-templates.md
  content/sensu-go/6.0/observability-pipeline/observe-process/handler-templates.md
  content/sensu-go/6.1/observability-pipeline/observe-process/handler-templates.md
Labels: new doc, ready for review

#2759 Document known caveats for sensuctl prune and the prune API
  content/sensu-go/5.19/api/prune.md
  content/sensu-go/5.19/sensuctl/create-manage-resources.md
  content/sensu-go/5.20/api/prune.md
  content/sensu-go/5.20/sensuctl/create-manage-resources.md
  content/sensu-go/5.21/api/prune.md
  content/sensu-go/5.21/sensuctl/create-manage-resources.md
  content/sensu-go/6.0/api/prune.md
  content/sensu-go/6.0/sensuctl/create-manage-resources.md
  content/sensu-go/6.1/api/prune.md
  content/sensu-go/6.1/sensuctl/create-manage-resources.md
Labels: ready for review, update
