Repository sensu/sensu-docs, pull requests merged in 2020-01, with the labels that each got.

#2069 Fix broken links in Federation and Backend docs
  content/sensu-go/5.15/guides/use-federation.md
  content/sensu-go/5.16/guides/use-federation.md
  content/sensu-go/5.16/reference/backend.md
Labels: bug

#2051 Add cluster role POST and PUT examples
  content/sensu-go/5.16/api/cluster-roles.md
Labels: ready for review, update

#2053 Add auth providers API examples
  content/sensu-go/5.16/api/authproviders.md
Labels: ready for review, update

#2055 Add POST example for etcd replicators in federation API doc
  content/sensu-go/5.16/api/federation.md
Labels: ready for review, update

#2064 Add POST and PUT examples in silenced API doc
  content/sensu-go/5.16/api/silenced.md
Labels: ready for review, update

#2060 Add POST and PUT examples in mutators API doc
  content/sensu-go/5.16/api/mutators.md
Labels: ready for review, update

#2061 Add POST and PUT examples in namespaces API doc
  content/sensu-go/5.16/api/namespaces.md
Labels: ready for review, update

#2062 Add POST and PUT examples in role bindings API doc
  content/sensu-go/5.16/api/role-bindings.md
Labels: ready for review, update

#2063 Add POST and PUT examples in roles API doc
  content/sensu-go/5.16/api/roles.md
Labels: ready for review, update

#2058 Add POST and PUT examples in hooks API doc
  content/sensu-go/5.16/api/hooks.md
Labels: ready for review, update

#2057 Add POST and PUT examples in handlers API doc
  content/sensu-go/5.16/api/handlers.md
Labels: ready for review, update

#2056 Add POST and PUT examples in filters API doc
  content/sensu-go/5.16/api/filters.md
Labels: ready for review, update

#2075 Update issue templates
  .github/ISSUE_TEMPLATE/content-issue.md
  .github/ISSUE_TEMPLATE/site-functionality.md
Labels: enhancement, ready for review

#2059 Add license GET, PUT, and DELETE examples
  content/sensu-go/5.16/api/license.md
Labels: ready for review, update

#2054 Add GET /events/:entity/:check example to Entity API doc
  content/sensu-go/5.16/api/events.md
Labels: ready for review, update

#2042 Add release notes and document env var for Enterprise 3.7
  content/sensu-enterprise/3.7/changelog.md
  content/sensu-enterprise/3.7/configuration.md
Labels: ready for review

#2044 Promote Core Enterprise 3.7 to latest
  config.toml
  layouts/partials/footer_js.html
  static.json
  themes/hugo-material-docs/layouts/partials/footer_js.html
Labels: ready for review

#2080 Delete ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: enhancement, ready for review

#2070 Expand intro in hooks reference
  content/sensu-go/5.16/getting-started/glossary.md
  content/sensu-go/5.16/reference/hooks.md
Labels: ready for review, update

#2007 Add "register your installation" message and link in docs footer
  layouts/partials/footer.html
  static/images/gopher-only-01.png
  static/stylesheets/scss/_footer.scss
Labels: enhancement, ready for review

#2065 Add POST and PUT examples in assets API doc
  content/sensu-go/5.16/api/assets.md
Labels: help wanted, update

#2084 Add and update apikeys API examples
  content/sensu-go/5.16/api/apikeys.md
Labels: ready for review, update

#2052 Add entity POST and PUT examples
  content/sensu-go/5.16/api/entities.md
Labels: help wanted, update

#2085 Add and update auth API examples
  content/sensu-go/5.16/api/auth.md
Labels: ready for review, update

#2086 Add and update check API examples
  content/sensu-go/5.16/api/checks.md
Labels: ready for review, update

#2087 Add and update cluster API examples
  content/sensu-go/5.16/api/cluster.md
Labels: ready for review, update

#2088 Update cluster role bindings API examples
  content/sensu-go/5.16/api/cluster-role-bindings.md
Labels: ready for review, update

#2089 Update datastore API examples
  content/sensu-go/5.16/api/datastore.md
Labels: ready for review, update

#2090 Update health API example
  content/sensu-go/5.16/api/health.md
Labels: ready for review, update

#2091 Update metrics API example
  content/sensu-go/5.16/api/metrics.md
Labels: ready for review, update

#2092 Update Tessen API examples
  content/sensu-go/5.16/api/tessen.md
Labels: ready for review, update

#2093 Update users API examples
  content/sensu-go/5.16/api/users.md
Labels: ready for review, update

#2094 Update version API example
  content/sensu-go/5.16/api/version.md
Labels: ready for review, update

#2098 Change SENSU_TOKEN to SENSU_ACCESS_TOKEN in API examples
  content/sensu-go/5.16/api/apikeys.md
  content/sensu-go/5.16/api/assets.md
  content/sensu-go/5.16/api/authproviders.md
  content/sensu-go/5.16/api/checks.md
  content/sensu-go/5.16/api/cluster-role-bindings.md
  content/sensu-go/5.16/api/cluster-roles.md
  content/sensu-go/5.16/api/cluster.md
  content/sensu-go/5.16/api/datastore.md
  content/sensu-go/5.16/api/entities.md
  content/sensu-go/5.16/api/events.md
  content/sensu-go/5.16/api/federation.md
  content/sensu-go/5.16/api/filters.md
  content/sensu-go/5.16/api/handlers.md
  content/sensu-go/5.16/api/hooks.md
  content/sensu-go/5.16/api/license.md
  content/sensu-go/5.16/api/mutators.md
  content/sensu-go/5.16/api/namespaces.md
  content/sensu-go/5.16/api/overview.md
  content/sensu-go/5.16/api/role-bindings.md
  content/sensu-go/5.16/api/roles.md
  content/sensu-go/5.16/api/silenced.md
  content/sensu-go/5.16/api/tessen.md
  content/sensu-go/5.16/api/users.md
  content/sensu-go/5.16/guides/use-apikey-feature.md
  content/sensu-go/5.16/reference/license.md
Labels: ready for review, update

#2101 Remove extra colons from notes in entities API reference
  content/sensu-go/5.16/api/entities.md
Labels: ready for review

#2103 Remove POST entities/entity endpoint from API doc
  content/sensu-go/5.13/api/entities.md
  content/sensu-go/5.14/api/entities.md
  content/sensu-go/5.15/api/entities.md
  content/sensu-go/5.16/api/entities.md
Labels: errata

#2072 Add email handler guide
  content/sensu-go/5.16/guides/email-handler.md
  content/sensu-go/5.16/guides/up-running-tutorial.md
  content/sensu-go/5.17/guides/email-handler.md
  content/sensu-go/5.17/guides/up-running-tutorial.md
Labels: new doc, ready for review

#2110 Add keepalive-handlers flag to agent and handlers reference
  content/sensu-go/5.17/reference/agent.md
  content/sensu-go/5.17/reference/handlers.md
Labels: update

#2100 Add interactive training section in Go docs
  content/sensu-go/5.16/learn/_index.md
  content/sensu-go/5.16/learn/learn-in-15.md
  content/sensu-go/5.16/learn/learn-sensu-go.md
  content/sensu-go/5.16/learn/up-and-running.md
  content/sensu-go/5.17/learn/_index.md
  content/sensu-go/5.17/learn/learn-in-15.md
  content/sensu-go/5.17/learn/learn-sensu-go.md
  content/sensu-go/5.17/learn/up-and-running.md
Labels: enhancement

#2120 Add secrets to sensuctl reference
  content/sensu-go/5.17/sensuctl/reference.md
Labels: ready for review

#2099 Replace asset curl commands in Guides with sensuctl asset add
  content/sensu-go/5.16/guides/contact-routing.md
  content/sensu-go/5.16/guides/influx-db-metric-handler.md
  content/sensu-go/5.16/guides/install-check-executables-with-assets.md
  content/sensu-go/5.16/guides/monitor-external-resources.md
  content/sensu-go/5.16/guides/monitor-server-resources.md
  content/sensu-go/5.16/guides/reduce-alert-fatigue.md
  content/sensu-go/5.16/guides/send-slack-alerts.md
  content/sensu-go/5.17/guides/contact-routing.md
  content/sensu-go/5.17/guides/influx-db-metric-handler.md
  content/sensu-go/5.17/guides/install-check-executables-with-assets.md
  content/sensu-go/5.17/guides/monitor-external-resources.md
  content/sensu-go/5.17/guides/monitor-server-resources.md
  content/sensu-go/5.17/guides/reduce-alert-fatigue.md
  content/sensu-go/5.17/guides/send-slack-alerts.md
Labels: ready for review, update

#2128 Add examples with secrets to checks, handlers, and mutators references
  content/sensu-go/5.17/reference/checks.md
  content/sensu-go/5.17/reference/handlers.md
  content/sensu-go/5.17/reference/mutators.md
Labels: ready for review, update

#2133 Replace sample-app.md with sensu-k8s-quick-start in sandbox page
  content/sensu-go/5.13/getting-started/sandbox.md
  content/sensu-go/5.14/getting-started/sandbox.md
  content/sensu-go/5.15/getting-started/sandbox.md
  content/sensu-go/5.16/getting-started/sandbox.md
  content/sensu-go/5.17/getting-started/sandbox.md
Labels: ready for review, update

#2132 Update UPN note in installation/auth
  content/sensu-go/5.17/installation/auth.md
Labels: ready for review, update

#2122 Add secrets API doc
  content/sensu-go/5.17/api/secrets.md
Labels: new doc, ready for review

#2124 Add sensu-backend-init for Docker and remove notes
  content/sensu-go/5.17/getting-started/sample-app.md
  content/sensu-go/5.17/installation/install-sensu.md
  content/sensu-go/5.17/reference/rbac.md
  content/sensu-go/5.17/sensuctl/quickstart.md
  content/sensu-go/5.17/sensuctl/reference.md
Labels: ready for review, update

#2137 Add event.entity.name supported for fieldSelector
  content/sensu-go/5.17/api/overview.md
Labels: ready for review, update

#2139 Add Secret to sensuctl create types
  content/sensu-go/5.17/sensuctl/reference.md
Labels: ready for review, update

#2140 Add VaultProvider to sensuctl create resource types
  content/sensu-go/5.17/sensuctl/reference.md
Labels: update

#2125 Add secrets reference
  content/sensu-go/5.17/reference/secrets.md
Labels: new doc, ready for review

#2126 Add secret providers reference doc
  content/sensu-go/5.17/reference/secrets-providers.md
Labels: new doc, ready for review

#2109 Add release notes for 5.17
  content/sensu-go/5.17/release-notes.md
Labels: update

#2048 Correct sensuctl command examples
  content/sensu-go/5.16/sensuctl/reference.md
  content/sensu-go/5.17/sensuctl/reference.md
Labels: errata, ready for review

#2130 "Use secrets management" guide
  content/sensu-go/5.17/guides/secrets-management.md
Labels: new doc, ready for review

#2144 Update secrets management guide
  content/sensu-go/5.17/guides/secrets-management.md
  static/images/sensu-pagerduty-integration-key.png
  static/images/vault-dev-root-token.png
Labels: errata

#2147 Remove hyphen in sensu-backend init in 5.17.0
  content/sensu-go/5.17/release-notes.md
Labels: errata

#2148 Add 5.17.1 release notes
  content/sensu-go/5.17/release-notes.md
Labels: update

#2149 Update supported versions page for 5.17.1
  content/sensu-go/5.17/getting-started/versions.md
Labels: update
