Repository sensu/sensu-docs, pull requests merged in 2020-07, with the labels that each got.

#2586 Update links in FAQ and add port heading to Install Sensu
  content/sensu-go/5.18/faq.md
  content/sensu-go/5.18/installation/install-sensu.md
  content/sensu-go/5.19/faq.md
  content/sensu-go/5.19/installation/install-sensu.md
  content/sensu-go/5.20/faq.md
  content/sensu-go/5.20/installation/install-sensu.md
  content/sensu-go/5.21/faq.md
  content/sensu-go/5.21/installation/install-sensu.md
Labels: improvement

#2593 Explain asset download timing in asset reference
  content/sensu-go/5.18/reference/assets.md
  content/sensu-go/5.19/reference/assets.md
  content/sensu-go/5.20/reference/assets.md
  content/sensu-go/5.21/reference/assets.md
Labels: improvement, ready for review

#2590 Add information about certificate bundles/chains
  content/sensu-go/5.18/reference/agent.md
  content/sensu-go/5.18/reference/backend.md
  content/sensu-go/5.19/reference/agent.md
  content/sensu-go/5.19/reference/backend.md
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.20/reference/backend.md
  content/sensu-go/5.21/reference/agent.md
  content/sensu-go/5.21/reference/backend.md
Labels: ready for review, update

#2600 Add asset build download note in all docs that involve adding an asset
  content/sensu-go/5.18/guides/contact-routing.md
  content/sensu-go/5.18/guides/email-handler.md
  content/sensu-go/5.18/guides/influx-db-metric-handler.md
  content/sensu-go/5.18/guides/install-check-executables-with-assets.md
  content/sensu-go/5.18/guides/monitor-external-resources.md
  content/sensu-go/5.18/guides/monitor-server-resources.md
  content/sensu-go/5.18/guides/reduce-alert-fatigue.md
  content/sensu-go/5.18/guides/send-slack-alerts.md
  content/sensu-go/5.18/sensuctl/sensuctl-bonsai.md
  content/sensu-go/5.19/guides/contact-routing.md
  content/sensu-go/5.19/guides/email-handler.md
  content/sensu-go/5.19/guides/influx-db-metric-handler.md
  content/sensu-go/5.19/guides/install-check-executables-with-assets.md
  content/sensu-go/5.19/guides/monitor-external-resources.md
  content/sensu-go/5.19/guides/monitor-server-resources.md
  content/sensu-go/5.19/guides/reduce-alert-fatigue.md
  content/sensu-go/5.19/guides/send-slack-alerts.md
  content/sensu-go/5.19/sensuctl/sensuctl-bonsai.md
  content/sensu-go/5.20/guides/contact-routing.md
  content/sensu-go/5.20/guides/email-handler.md
  content/sensu-go/5.20/guides/influx-db-metric-handler.md
  content/sensu-go/5.20/guides/install-check-executables-with-assets.md
  content/sensu-go/5.20/guides/monitor-external-resources.md
  content/sensu-go/5.20/guides/monitor-server-resources.md
  content/sensu-go/5.20/guides/reduce-alert-fatigue.md
  content/sensu-go/5.20/guides/send-slack-alerts.md
  content/sensu-go/5.20/sensuctl/sensuctl-bonsai.md
  content/sensu-go/5.21/guides/contact-routing.md
  content/sensu-go/5.21/guides/email-handler.md
  content/sensu-go/5.21/guides/influx-db-metric-handler.md
  content/sensu-go/5.21/guides/install-check-executables-with-assets.md
  content/sensu-go/5.21/guides/monitor-external-resources.md
  content/sensu-go/5.21/guides/monitor-server-resources.md
  content/sensu-go/5.21/guides/reduce-alert-fatigue.md
  content/sensu-go/5.21/guides/send-slack-alerts.md
  content/sensu-go/5.21/sensuctl/sensuctl-bonsai.md
Labels: improvement, ready for review

#2607 Copy change in fixed windows powershell asset path env variable eval for JSON example
  content/sensu-go/5.21/reference/assets.md
Labels: ready for review

#2592 Clarify environment variables and assetPath function in assets reference
  content/sensu-go/5.21/reference/assets.md
Labels: errata, ready for review

#2452 Add script for creating a new version of docs
  scripts/new-docs-version.sh
Labels: enhancement

#2608 Enable clicking on top-level menu items
  layouts/partials/nav.html
Labels: ready for review

#2613 Add "Contribute" section to sidebar
  layouts/_default/single.html
  layouts/partials/contribute.html
  static/stylesheets/scss/_layout.scss
  static/stylesheets/scss/_sidebar.scss
  static/stylesheets/scss/_toc.scss
  static/stylesheets/scss/main.scss
Labels: ready for review

#2621 Make Sensu Core 1.7 requirement more prominent in Migrate doc
  content/sensu-go/5.18/migrate.md
  content/sensu-go/5.19/migrate.md
  content/sensu-go/5.20/migrate.md
  content/sensu-go/5.21/migrate.md
Labels: improvement

#2627 Add improved sensuctl asset add response with help usage
  content/sensu-go/6.0/guides/contact-routing.md
  content/sensu-go/6.0/guides/email-handler.md
  content/sensu-go/6.0/guides/influx-db-metric-handler.md
  content/sensu-go/6.0/guides/install-check-executables-with-assets.md
  content/sensu-go/6.0/guides/monitor-external-resources.md
  content/sensu-go/6.0/guides/monitor-server-resources.md
  content/sensu-go/6.0/guides/reduce-alert-fatigue.md
  content/sensu-go/6.0/guides/send-slack-alerts.md
  content/sensu-go/6.0/sensuctl/sensuctl-bonsai.md
Labels: ready for review

#2626 Add memberOf attribute to Configure Authentication
  content/sensu-go/6.0/operations/control-access/auth.md
Labels: ready for review

#2635 Add is_silenced to event examples and spec
  content/sensu-go/6.0/api/events.md
  content/sensu-go/6.0/reference/events.md
Labels: ready for review

#2642 Clarify notes about process discovery
  content/sensu-go/5.20/reference/agent.md
  content/sensu-go/5.20/reference/entities.md
  content/sensu-go/5.21/reference/agent.md
  content/sensu-go/5.21/reference/entities.md
  content/sensu-go/6.0/reference/agent.md
  content/sensu-go/6.0/reference/entities.md
Labels: improvement

#2589 Add best practice info to Run a Sensu cluster
  content/sensu-go/5.18/operations/deploy-sensu/cluster-sensu.md
  content/sensu-go/5.19/operations/deploy-sensu/cluster-sensu.md
  content/sensu-go/5.20/operations/deploy-sensu/cluster-sensu.md
  content/sensu-go/5.21/operations/deploy-sensu/cluster-sensu.md
  content/sensu-go/6.0/operations/deploy-sensu/cluster-sensu.md
Labels: improvement, ready for review

#2637 Correct Sensu requirement re: secret/ path for Vault secrets
  content/sensu-go/5.18/operations/manage-secrets/secrets-management.md
  content/sensu-go/5.18/reference/secrets.md
  content/sensu-go/5.19/operations/manage-secrets/secrets-management.md
  content/sensu-go/5.19/reference/secrets.md
  content/sensu-go/5.20/operations/manage-secrets/secrets-management.md
  content/sensu-go/5.20/reference/secrets.md
  content/sensu-go/5.21/operations/manage-secrets/secrets-management.md
  content/sensu-go/5.21/reference/secrets.md
  content/sensu-go/6.0/operations/manage-secrets/secrets-management.md
  content/sensu-go/6.0/reference/secrets.md
Labels: errata, ready for review

#2649 Fix link to OIDC spec attributes
  content/sensu-go/5.18/operations/control-access/auth.md
  content/sensu-go/5.19/operations/control-access/auth.md
  content/sensu-go/5.20/operations/control-access/auth.md
  content/sensu-go/5.21/operations/control-access/auth.md
  content/sensu-go/6.0/operations/control-access/auth.md
Labels: errata

#2638 Add sections about creating and modifying agent and proxy entities
  content/sensu-go/6.0/reference/agent.md
  content/sensu-go/6.0/reference/entities.md
Labels: ready for review

#2640 Add section in event filter reference for JS functions and add new SQE to SQE reference
  content/sensu-go/6.0/commercial.md
  content/sensu-go/6.0/reference/filters.md
  content/sensu-go/6.0/reference/sensu-query-expressions.md
Labels: ready for review

#2622 Add instructions for upgrading from 5.x to 6.0
  content/sensu-go/6.0/operations/maintain-sensu/upgrade.md
Labels: ready for review

#2568 Fixing monitoring guide
  content/sensu-go/5.21/guides/monitor-sensu.md
  package.json
  static/images/sensu-postgres-health.png
Labels: new doc, ready for review

#2624 Add new 6.0 packages and binary distributions in supported platforms
  content/sensu-go/6.0/platforms.md
Labels: ready for review
